// Code generated by "shoot map -path=../../domain/model -alias=domain -type=*"; DO NOT EDIT.

package po

import domain "mappersample/domain/model"

// ToDomain converts receiver to type domain.Order
func (o *Order) ToDomain() *domain.Order {
	order_ := new(domain.Order)
	order_.ID = o.ID
	order_.Amount = o.Amount
	order_.Status = o.Status
	order_.OrderTime = o.OrderTime
	o.writeDomain(order_)
	return order_
}

// FromDomain read from type domain.Order, then write back to receiver
func (o *Order) FromDomain(order_ *domain.Order) *Order {
	o.ID = order_.ID
	o.Amount = order_.Amount
	o.Status = order_.Status
	o.OrderTime = order_.OrderTime
	o.NullTime = o.TimePtrToNullTime(order_.NullTime)
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o Order) ShootMap() { /*noop*/ }

// ToDomain converts receiver to type domain.User
func (u *User) ToDomain() *domain.User {
	user_ := new(domain.User)
	user_.FirstName = u.FirstName
	user_.LastName = u.LastName
	user_.Email = u.Email
	if u.AddressList != nil {
		user_.AddressList = make([]domain.UserAddress, len(u.AddressList))
		for _i, _x := range u.AddressList {
			if u.AddressList != nil {
				user_.AddressList[_i] = *_x.ToDomain()
			}
		}
	}
	u.writeDomain(user_)
	return user_
}

// FromDomain read from type domain.User, then write back to receiver
func (u *User) FromDomain(user_ *domain.User) *User {
	u.FirstName = user_.FirstName
	u.LastName = user_.LastName
	u.Email = user_.Email
	if user_.AddressList != nil {
		u.AddressList = make([]*UserAddress, len(user_.AddressList))
		for _i, _x := range user_.AddressList {
			u.AddressList[_i] = new(UserAddress).FromDomain(&_x)
		}
	}
	return u
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (u User) ShootMap() { /*noop*/ }

// ToDomain converts receiver to type domain.UserAddress
func (u *UserAddress) ToDomain() *domain.UserAddress {
	userAddress_ := new(domain.UserAddress)
	userAddress_.City = u.City
	userAddress_.Street = u.Street
	userAddress_.Room = u.Room
	userAddress_.Tag = u.Tag
	userAddress_.IsDefault = u.IsDefault
	userAddress_.OwnerID = u.UserID
	u.writeDomain(userAddress_)
	return userAddress_
}

// FromDomain read from type domain.UserAddress, then write back to receiver
func (u *UserAddress) FromDomain(userAddress_ *domain.UserAddress) *UserAddress {
	u.City = userAddress_.City
	u.Street = userAddress_.Street
	u.Room = userAddress_.Room
	u.Tag = userAddress_.Tag
	u.IsDefault = userAddress_.IsDefault
	u.UserID = userAddress_.OwnerID
	return u
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (u UserAddress) ShootMap() { /*noop*/ }
