// Code generated by "shoot map -path=../../domain/model -alias=domain -type=Order,User,UserAddress"; DO NOT EDIT. (v0.3.2-beta.5)

package po

import domain "mappersample/domain/model"

// ToDomain converts receiver to type domain.Order
func (o *Order) ToDomain() *domain.Order {
	if o == nil {
		return nil
	}
	order_ := new(domain.Order)
	order_.ID = o.ID
	order_.Amount = o.Amount
	order_.Status = o.Status
	order_.OrderTime = o.OrderTime
	return order_
}

// FromDomain reads from type domain.Order, then writes back to receiver and returns it
func (o *Order) FromDomain(order_ *domain.Order) *Order {
	if order_ == nil {
		return o
	}
	if o == nil {
		o = new(Order)
	}
	o.ID = order_.ID
	o.Amount = order_.Amount
	o.Status = order_.Status
	o.OrderTime = order_.OrderTime
	o.readDomain(*order_)
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o Order) ShootMap() { /*noop*/ }
