// Code generated by "shoot map -path=../../domain/model -type=Order"; DO NOT EDIT.

package po

import "mappersample/domain/model"

// ToModel converts receiver type to type model.Order
func (o *Order) ToModel() *model.Order {
	order_ := new(model.Order)
	order_.ID = o.ID
	order_.Amount = o.Amount
	order_.Status = o.Status
	return order_
}

// FromModel converts from type model.Order to receiver type
func (o *Order) FromModel(order_ *model.Order) *Order {
	o.ID = order_.ID
	o.Amount = order_.Amount
	o.Status = order_.Status
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o Order) ShootMap() { /*noop*/ }
