// Code generated by "shoot map -path=../../domain/model -alias=domain -type=UserAddress"; DO NOT EDIT.

package po

import domain "mappersample/domain/model"

// ToDomain converts receiver to type domain.UserAddress
func (u *UserAddress) ToDomain() *domain.UserAddress {
	if u == nil {
		return nil
	}
	userAddress_ := new(domain.UserAddress)
	userAddress_.City = u.City
	userAddress_.Street = u.Street
	userAddress_.Room = u.Room
	userAddress_.Tag = u.Tag
	userAddress_.IsDefault = u.IsDefault
	userAddress_.OwnerID = u.UserID
	u.writeDomain(userAddress_)
	return userAddress_
}

// FromDomain read from type domain.UserAddress, then write back to receiver
func (u *UserAddress) FromDomain(userAddress_ *domain.UserAddress) *UserAddress {
	if userAddress_ == nil {
		return u
	}
	if u == nil {
		u = new(UserAddress)
	}
	u.City = userAddress_.City
	u.Street = userAddress_.Street
	u.Room = userAddress_.Room
	u.Tag = userAddress_.Tag
	u.IsDefault = userAddress_.IsDefault
	u.UserID = userAddress_.OwnerID
	return u
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (u UserAddress) ShootMap() { /*noop*/ }
