// Code generated by "shoot map -path=../../domain/model -type=User"; DO NOT EDIT.

package po

import "mappersample/domain/model"

// ToModel converts receiver to type model.User
func (u *User) ToModel() *model.User {
	user_ := new(model.User)
	user_.FirstName = u.FirstName
	user_.LastName = u.LastName
	user_.Email = u.Email
	return user_
}

// FromModel read from type model.User, then write back to receiver
func (u *User) FromModel(user_ *model.User) *User {
	u.FirstName = user_.FirstName
	u.LastName = user_.LastName
	u.Email = user_.Email
	return u
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (u User) ShootMap() { /*noop*/ }
