// Code generated by "shoot map -path=../../domain/model -alias=domain -type=Order,User,UserAddress"; DO NOT EDIT. (v0.3.2-beta.5)

package po

import (
	domain "mappersample/domain/model"

	"gorm.io/gorm"
)

// ToDomain converts receiver to type domain.UserAddress
func (u *UserAddress) ToDomain() *domain.UserAddress {
	if u == nil {
		return nil
	}
	userAddress_ := new(domain.UserAddress)
	if u.Model != nil {
		userAddress_.ID = u.ID
	}
	userAddress_.City = u.City
	userAddress_.Street = u.Street
	userAddress_.Room = u.Room
	userAddress_.Tag = u.Tag
	userAddress_.IsDefault = u.IsDefault
	userAddress_.OwnerID = u.UserID
	u.writeDomain(userAddress_)
	return userAddress_
}

// FromDomain reads from type domain.UserAddress, then writes back to receiver and returns it
func (u *UserAddress) FromDomain(userAddress_ *domain.UserAddress) *UserAddress {
	if userAddress_ == nil {
		return u
	}
	if u == nil {
		u = new(UserAddress)
	}
	if u.Model == nil {
		u.Model = new(gorm.Model)
	}
	u.ID = userAddress_.ID
	u.City = userAddress_.City
	u.Street = userAddress_.Street
	u.Room = userAddress_.Room
	u.Tag = userAddress_.Tag
	u.IsDefault = userAddress_.IsDefault
	u.UserID = userAddress_.OwnerID
	u.readDomain(userAddress_)
	return u
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (u UserAddress) ShootMap() { /*noop*/ }
