// Code generated by "shoot map -path=../../domain/model -alias=domain -type=User -v"; DO NOT EDIT.

package po

import domain "mappersample/domain/model"

// ToDomain converts receiver to type domain.User
func (u *User) ToDomain() *domain.User {
	user_ := new(domain.User)
	user_.FirstName = u.FirstName
	user_.LastName = u.LastName
	user_.Email = u.Email
	u.writeModel(user_)
	return user_
}

// FromDomain read from type domain.User, then write back to receiver
func (u *User) FromDomain(user_ *domain.User) *User {
	u.FirstName = user_.FirstName
	u.LastName = user_.LastName
	u.Email = user_.Email
	return u
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (u User) ShootMap() { /*noop*/ }
