// Code generated by "shoot new -getset -opt -type=RestConf"; DO NOT EDIT.

package shoot

// NewRestConf constructs a new instance of type RestConf
func NewRestConf(baseURL string, timeout int) *RestConf {
	return &RestConf{
		baseURL: baseURL,
		timeout: timeout,
	}
}

// With initializes this instance using the functional options pattern
func (r *RestConf) With(opts ...Option[RestConf, *RestConf]) *RestConf {
	r.SetDefault()
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// BaseURLOfRestConf is a configuration for the filed baseURL
func BaseURLOfRestConf(baseurl_ string) Option[RestConf, *RestConf] {
	return func(r *RestConf) {
		r.baseURL = baseurl_
	}
}

// TimeoutOfRestConf is a configuration for the filed timeout
func TimeoutOfRestConf(timeout_ int) Option[RestConf, *RestConf] {
	return func(r *RestConf) {
		r.timeout = timeout_
	}
}

// SetDefault sets the default values
func (r *RestConf) SetDefault() {}

// BaseURL gets the value of field baseURL
func (r *RestConf) BaseURL() string {
	return r.baseURL
}

// Timeout gets the value of field timeout
func (r *RestConf) Timeout() int {
	return r.timeout
}

// SetBaseURL sets the value of field baseURL
func (r *RestConf) SetBaseURL(baseURL_ string) {
	r.baseURL = baseURL_
}

// SetTimeout sets the value of field timeout
func (r *RestConf) SetTimeout(timeout_ int) {
	r.timeout = timeout_
}
