// Code generated by "shoot new -opt -type=Conf2"; DO NOT EDIT.

package model

// NewConf2 constructs a new instance of type Conf2
func NewConf2(name string) *Conf2 {
	return &Conf2{
		name: name,
	}
}

// With initializes this instance using the functional options pattern
func (c *Conf2) With(opts ..._opt_[Conf2, *Conf2]) *Conf2 {
	c._def_()
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func NameOfConf2(name string) _opt_[Conf2, *Conf2] {
	return func(c *Conf2) {
		c.name = name
	}
}

func HostOfConf2(host string) _opt_[Conf2, *Conf2] {
	return func(c *Conf2) {
		c.host = host
	}
}

func PortOfConf2(port int) _opt_[Conf2, *Conf2] {
	return func(c *Conf2) {
		c.port = port
	}
}

func (c *Conf2) _def_() {
	c.host = "localhost"
	c.port = 80

}
