// Code generated by "shoot new -getset -json -type=User"; DO NOT EDIT.

package model

import "encoding/json"

// NewUser constructs a new instance of type User
func NewUser(id string, name string, gender int, age int, tel string) *User {
	return &User{
		id:     id,
		name:   name,
		gender: gender,
		age:    age,
		tel:    tel,
	}
}

// Id gets the value of field id
func (u *User) Id() string {
	return u.id
}

// Name gets the value of field name
func (u *User) Name() string {
	return u.name
}

// Gender gets the value of field gender
func (u *User) Gender() int {
	return u.gender
}

// Age gets the value of field age
func (u *User) Age() int {
	return u.age
}

// Tel gets the value of field tel
func (u *User) Tel() string {
	return u.tel
}

// SetId sets the value of field id
func (u *User) SetId(id string) {
	u.id = id
}

// SetName sets the value of field name
func (u *User) SetName(name string) {
	u.name = name
}

// SetGender sets the value of field gender
func (u *User) SetGender(gender int) {
	u.gender = gender
}

// SetAge sets the value of field age
func (u *User) SetAge(age int) {
	u.age = age
}

// SetTel sets the value of field tel
func (u *User) SetTel(tel string) {
	u.tel = tel
}

type _User_marshal struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Gender int    `json:"gender"`
	Age    int    `json:"age"`
	Tel    string `json:"tel"`
}

type _User_unmarshal struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Gender int    `json:"gender"`
	Age    int    `json:"age"`
	Tel    string `json:"tel"`
}

// MarshalJSON serializes type User to json bytes
func (u User) MarshalJSON() ([]byte, error) {
	data := _User_marshal{
		Id:     u.Id(),
		Name:   u.Name(),
		Gender: u.Gender(),
		Age:    u.Age(),
		Tel:    u.Tel(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type User
func (u *User) UnmarshalJSON(data []byte) error {
	var user_ _User_unmarshal
	if err := json.Unmarshal(data, &user_); err != nil {
		return nil
	}

	u.SetId(user_.Id)
	u.SetName(user_.Name)
	u.SetGender(user_.Gender)
	u.SetAge(user_.Age)
	u.SetTel(user_.Tel)
	return nil
}
