// Code generated by "shoot new -opt -type=Conf"; DO NOT EDIT.

package model

// NewConf constructs a new instance of type Conf
func NewConf(name string, host string, port int) *Conf {
	return &Conf{
		name: name,
		host: host,
		port: port,
	}
}

// With initializes this instance using the functional options pattern
func (c *Conf) With(opts ..._opt_[Conf, *Conf]) *Conf {
	c._def_()
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func NameOfConf(name string) _opt_[Conf, *Conf] {
	return func(c *Conf) {
		c.name = name
	}
}

func HostOfConf(host string) _opt_[Conf, *Conf] {
	return func(c *Conf) {
		c.host = host
	}
}

func PortOfConf(port int) _opt_[Conf, *Conf] {
	return func(c *Conf) {
		c.port = port
	}
}

func (c *Conf) _def_() {

}
