// Code generated by "shoot new -getset -json -v base.go"; DO NOT EDIT.

package model

import (
	dto2 "constructorsample/model/dto"
	"encoding/json"
)

// NewSon constructs a new instance of type Son
func NewSon(name string) *Son {
	return &Son{
		name: name,
	}
}

// Name gets the value of field name
func (s *Son) Name() string {
	return s.name
}

// SetName sets the value of field name
func (s *Son) SetName(name_ string) {
	s.name = name_
}

type _Son_marshal struct {
	Base
	dto2.Class

	Name string `json:"name"`
}

type _Son_unmarshal struct {
	Base
	dto2.Class

	Name string `json:"name"`
}

// MarshalJSON serializes type Son to json bytes
func (s Son) MarshalJSON() ([]byte, error) {
	data := _Son_marshal{
		Base:  s.Base,
		Class: s.Class,

		Name: s.Name(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Son
func (s *Son) UnmarshalJSON(data []byte) error {
	var son_ _Son_unmarshal
	if err := json.Unmarshal(data, &son_); err != nil {
		return nil
	}
	s.SetName(son_.Name)

	s.Base = son_.Base
	s.Class = son_.Class

	return nil
}
