// Code generated by "shoot new -getset -json base.go"; DO NOT EDIT.

package model

import "encoding/json"

// NewBase constructs a new instance of type Base
func NewBase(id int) *Base {
	return &Base{
		id: id,
	}
}

// Id gets the value of field id
func (b *Base) Id() int {
	return b.id
}

// SetId sets the value of field id
func (b *Base) SetId(id_ int) {
	b.id = id_
}

type _Base_marshal struct {
	Id int `json:"id"`
}

type _Base_unmarshal struct {
	Id int `json:"id"`
}

// MarshalJSON serializes type Base to json bytes
func (b Base) MarshalJSON() ([]byte, error) {
	data := _Base_marshal{
		Id: b.Id(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Base
func (b *Base) UnmarshalJSON(data []byte) error {
	var base_ _Base_unmarshal
	if err := json.Unmarshal(data, &base_); err != nil {
		return nil
	}

	b.SetId(base_.Id)
	return nil
}
