// Code generated by "shoot new -getset -json base.go"; DO NOT EDIT.

package model

import "encoding/json"

// NewSon constructs a new instance of type Son
func NewSon(name string) *Son {
	return &Son{
		name: name,
	}
}

// Name gets the value of field name
func (s *Son) Name() string {
	return s.name
}

// SetName sets the value of field name
func (s *Son) SetName(name_ string) {
	s.name = name_
}

type _Son_marshal struct {
	Name string `json:"name"`
}

type _Son_unmarshal struct {
	Name string `json:"name"`
}

// MarshalJSON serializes type Son to json bytes
func (s Son) MarshalJSON() ([]byte, error) {
	data := _Son_marshal{
		Name: s.Name(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Son
func (s *Son) UnmarshalJSON(data []byte) error {
	var son_ _Son_unmarshal
	if err := json.Unmarshal(data, &son_); err != nil {
		return nil
	}

	s.SetName(son_.Name)
	return nil
}
