// Code generated by "shoot new -type=Conf"; DO NOT EDIT.

package model

// NewConf constructs a new instance of type Conf
func NewConf(name string, host string, port int) *Conf {
	return &Conf{
		name: name,
		host: host,
		port: port,
	}
}
