// Code generated by "shoot new -getset -opt -type=Conf"; DO NOT EDIT. (v0.4.2-beta.2)

package model

import "github.com/lopolopen/shoot"

// NewConf constructs a new instance of type Conf
func NewConf(name string, key1 string) *Conf {
	return &Conf{
		name: name,
		port: 80,
		key1: key1,
		key2: "key",
	}
}

// With initializes this instance using the functional options pattern
func (c *Conf) With(opts ...shoot.Option[Conf, *Conf]) *Conf {
	c.SetDefault()
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// NameOfConf is a configuration for the filed name
func NameOfConf(name_ string) shoot.Option[Conf, *Conf] {
	return func(c *Conf) {
		c.name = name_
	}
}

// HostOfConf is a configuration for the filed host
func HostOfConf(host_ []string) shoot.Option[Conf, *Conf] {
	return func(c *Conf) {
		c.host = host_
	}
}

// PortOfConf is a configuration for the filed port
func PortOfConf(port_ int) shoot.Option[Conf, *Conf] {
	return func(c *Conf) {
		c.port = port_
	}
}

// Key1OfConf is a configuration for the filed key1
func Key1OfConf(key1_ string) shoot.Option[Conf, *Conf] {
	return func(c *Conf) {
		c.key1 = key1_
	}
}

// Key2OfConf is a configuration for the filed key2
func Key2OfConf(key2_ string) shoot.Option[Conf, *Conf] {
	return func(c *Conf) {
		c.key2 = key2_
	}
}

// SetDefault sets the default values
func (c *Conf) SetDefault() {
	c.port = 80
	c.key1 = "key"
	c.key2 = "key"
}

// Name gets the value of field name
func (c *Conf) Name() string {
	return c.name
}

// Host gets the value of field host
func (c *Conf) Host() []string {
	return c.host
}

// Port gets the value of field port
func (c *Conf) Port() int {
	return c.port
}

// Key1 gets the value of field key1
func (c *Conf) Key1() string {
	return c.key1
}

// Key2 gets the value of field key2
func (c *Conf) Key2() string {
	return c.key2
}

// SetName sets the value of field name
func (c *Conf) SetName(name_ string) {
	c.name = name_
}

// SetHost sets the value of field host
func (c *Conf) SetHost(host_ []string) {
	c.host = host_
}

// SetPort sets the value of field port
func (c *Conf) SetPort(port_ int) {
	c.port = port_
}

// SetKey1 sets the value of field key1
func (c *Conf) SetKey1(key1_ string) {
	c.key1 = key1_
}

// SetKey2 sets the value of field key2
func (c *Conf) SetKey2(key2_ string) {
	c.key2 = key2_
}

// ConfGetter is read-only interface for Conf type
type ConfGetter interface {
	Name() string
	Host() []string
	Port() int
	Key1() string
	Key2() string
}

// ConfSetter is write-only interface for Conf type
type ConfSetter interface {
	SetName(string)
	SetHost([]string)
	SetPort(int)
	SetKey1(string)
	SetKey2(string)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (c Conf) ShootNew() { /*noop*/ }
