// Code generated by "shoot new -getset -json -file=resp.go"; DO NOT EDIT. (v0.3.2-beta.5)

package model

import "encoding/json"

// NewPageResult constructs a new instance of type PageResult
func NewPageResult(perPage int, page int, totalPage int) *PageResult {
	return &PageResult{
		perPage:   perPage,
		page:      page,
		totalPage: totalPage,
	}
}

// PerPage gets the value of field perPage
func (p *PageResult) PerPage() int {
	return p.perPage
}

// Page gets the value of field page
func (p *PageResult) Page() int {
	return p.page
}

// TotalPage gets the value of field totalPage
func (p *PageResult) TotalPage() int {
	return p.totalPage
}

// SetPerPage sets the value of field perPage
func (p *PageResult) SetPerPage(perPage_ int) {
	p.perPage = perPage_
}

// SetPage sets the value of field page
func (p *PageResult) SetPage(page_ int) {
	p.page = page_
}

// SetTotalPage sets the value of field totalPage
func (p *PageResult) SetTotalPage(totalPage_ int) {
	p.totalPage = totalPage_
}

type _PageResult_marshal struct {
	PerPage   int `json:"perPage"`
	Page      int `json:"page"`
	TotalPage int `json:"totalPage"`
}
type _PageResult_unmarshal struct {
	PerPage   int `json:"perPage"`
	Page      int `json:"page"`
	TotalPage int `json:"totalPage"`
}

// MarshalJSON serializes type PageResult to json bytes
func (p PageResult) MarshalJSON() ([]byte, error) {
	data := _PageResult_marshal{
		PerPage:   p.PerPage(),
		Page:      p.Page(),
		TotalPage: p.TotalPage(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type PageResult
func (p *PageResult) UnmarshalJSON(data []byte) error {
	var pageResult_ _PageResult_unmarshal
	if err := json.Unmarshal(data, &pageResult_); err != nil {
		return err
	}
	p.SetPerPage(pageResult_.PerPage)
	p.SetPage(pageResult_.Page)
	p.SetTotalPage(pageResult_.TotalPage)
	return nil
}

// PageResultGetter is read-only interface for PageResult type
type PageResultGetter interface {
	PerPage() int
	Page() int
	TotalPage() int
}

// PageResultSetter is write-only interface for PageResult type
type PageResultSetter interface {
	SetPerPage(int)
	SetPage(int)
	SetTotalPage(int)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (p PageResult) ShootNew() { /*noop*/ }

// NewResp constructs a new instance of type Resp
func NewResp(code int, msg string) *Resp {
	return &Resp{
		code: code,
		msg:  msg,
	}
}

// Code gets the value of field code
func (r *Resp) Code() int {
	return r.code
}

// Msg gets the value of field msg
func (r *Resp) Msg() string {
	return r.msg
}

// SetCode sets the value of field code
func (r *Resp) SetCode(code_ int) {
	r.code = code_
}

// SetMsg sets the value of field msg
func (r *Resp) SetMsg(msg_ string) {
	r.msg = msg_
}

type _Resp_marshal struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
type _Resp_unmarshal struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

// MarshalJSON serializes type Resp to json bytes
func (r Resp) MarshalJSON() ([]byte, error) {
	data := _Resp_marshal{
		Code: r.Code(),
		Msg:  r.Msg(),
	}
	values := make(map[string]interface{})
	j0, err := json.Marshal(r.PageResult)
	if err != nil {
		return nil, err
	}
	err = json.Unmarshal(j0, &values)
	if err != nil {
		return nil, err
	}
	j, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	err = json.Unmarshal(j, &values)
	if err != nil {
		return nil, err
	}
	return json.Marshal(values)
}

// UnmarshalJSON deserializes json bytes to type Resp
func (r *Resp) UnmarshalJSON(data []byte) error {
	var resp_ _Resp_unmarshal
	if err := json.Unmarshal(data, &resp_); err != nil {
		return err
	}
	r.SetCode(resp_.Code)
	r.SetMsg(resp_.Msg)
	all := make(map[string]interface{})
	err := json.Unmarshal(data, &all)
	if err != nil {
		return err
	}
	j, err := json.Marshal(resp_)
	if err != nil {
		return err
	}
	some := make(map[string]interface{})
	err = json.Unmarshal(j, &some)
	if err != nil {
		return err
	}
	for key := range some {
		delete(all, key)
	}
	jrest, err := json.Marshal(all)
	if err != nil {
		return err
	}
	err = json.Unmarshal(jrest, &r.PageResult)
	if err != nil {
		return err
	}
	return nil
}

// RespGetter is read-only interface for Resp type
type RespGetter interface {
	Code() int
	Msg() string
}

// RespSetter is write-only interface for Resp type
type RespSetter interface {
	SetCode(int)
	SetMsg(string)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (r Resp) ShootNew() { /*noop*/ }

// NewUserResp constructs a new instance of type UserResp
func NewUserResp(data *User) *UserResp {
	return &UserResp{
		data: data,
	}
}

// Data gets the value of field data
func (u *UserResp) Data() *User {
	return u.data
}

// SetData sets the value of field data
func (u *UserResp) SetData(data_ *User) {
	u.data = data_
}

type _UserResp_marshal struct {
	Data *User `json:"data"`
}
type _UserResp_unmarshal struct {
	Data *User `json:"data"`
}

// MarshalJSON serializes type UserResp to json bytes
func (u UserResp) MarshalJSON() ([]byte, error) {
	data := _UserResp_marshal{
		Data: u.Data(),
	}
	values := make(map[string]interface{})
	j0, err := json.Marshal(u.Resp)
	if err != nil {
		return nil, err
	}
	err = json.Unmarshal(j0, &values)
	if err != nil {
		return nil, err
	}
	j, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	err = json.Unmarshal(j, &values)
	if err != nil {
		return nil, err
	}
	return json.Marshal(values)
}

// UnmarshalJSON deserializes json bytes to type UserResp
func (u *UserResp) UnmarshalJSON(data []byte) error {
	var userResp_ _UserResp_unmarshal
	if err := json.Unmarshal(data, &userResp_); err != nil {
		return err
	}
	u.SetData(userResp_.Data)
	all := make(map[string]interface{})
	err := json.Unmarshal(data, &all)
	if err != nil {
		return err
	}
	j, err := json.Marshal(userResp_)
	if err != nil {
		return err
	}
	some := make(map[string]interface{})
	err = json.Unmarshal(j, &some)
	if err != nil {
		return err
	}
	for key := range some {
		delete(all, key)
	}
	jrest, err := json.Marshal(all)
	if err != nil {
		return err
	}
	err = json.Unmarshal(jrest, &u.Resp)
	if err != nil {
		return err
	}
	return nil
}

// UserRespGetter is read-only interface for UserResp type
type UserRespGetter interface {
	Data() *User
}

// UserRespSetter is write-only interface for UserResp type
type UserRespSetter interface {
	SetData(*User)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (u UserResp) ShootNew() { /*noop*/ }
