// Code generated by "shoot new -type User"; DO NOT EDIT.

package model

// NewUser constructs a new instance of type User
func NewUser(
	name string,
	age int,
) *User {
	return &User{
		name: name,
		age:  age,
	}
}

// Name gets the value of field name
func (u *User) Name() string {
	return u.name
}

// Age gets the value of field age
func (u *User) Age() int {
	return u.age
}

// Age sets the value of field age
func (u *User) SetAge(age int) {
	u.age = age
}
