// Code generated by "shoot new -type=Book"; DO NOT EDIT.

package model

import (
	"constructorsample/model/dto"
)

// NewBook constructs a new instance of type Book
func NewBook(name string, names []string, nameMap map[string]string, userMap map[string]User, owner *User, c *dto.Class) *Book {
	return &Book{
		name:    name,
		names:   names,
		nameMap: nameMap,
		userMap: userMap,
		owner:   owner,
		c:       c,
	}
}
