// Code generated by "shoot new -getset -json -file=user.go"; DO NOT EDIT.

package model

import "encoding/json"

// NewUser constructs a new instance of type User
func NewUser(id string, name string, gender int, age int, tel string) *User {
	return &User{
		id:     id,
		name:   name,
		gender: gender,
		age:    age,
		tel:    tel,
	}
}

// Id gets the value of field id
func (u *User) Id() string {
	return u.id
}

// Name gets the value of field name
func (u *User) Name() string {
	return u.name
}

// Gender gets the value of field gender
func (u *User) Gender() int {
	return u.gender
}

// Age gets the value of field age
func (u *User) Age() int {
	return u.age
}

// Tel gets the value of field tel
func (u *User) Tel() string {
	return u.tel
}

// SetName sets the value of field name
func (u *User) SetName(name_ string) {
	u.name = name_
}

// SetGender sets the value of field gender
func (u *User) SetGender(gender_ int) {
	u.gender = gender_
}

// SetAge sets the value of field age
func (u *User) SetAge(age_ int) {
	u.age = age_
}

// SetTel sets the value of field tel
func (u *User) SetTel(tel_ string) {
	u.tel = tel_
}

type _User_marshal struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Gender int    `json:"gender"`
	Age    int    `json:"age"`
	Tel    string `json:"tel"`
}
type _User_unmarshal struct {
	Name   string `json:"name"`
	Gender int    `json:"gender"`
	Age    int    `json:"age"`
	Tel    string `json:"tel"`
}

// MarshalJSON serializes type User to json bytes
func (u User) MarshalJSON() ([]byte, error) {
	data := _User_marshal{
		Id:     u.Id(),
		Name:   u.Name(),
		Gender: u.Gender(),
		Age:    u.Age(),
		Tel:    u.Tel(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type User
func (u *User) UnmarshalJSON(data []byte) error {
	var user_ _User_unmarshal
	if err := json.Unmarshal(data, &user_); err != nil {
		return err
	}
	u.SetName(user_.Name)
	u.SetGender(user_.Gender)
	u.SetAge(user_.Age)
	u.SetTel(user_.Tel)

	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (u User) ShootNew() { /*noop*/ }

// NewBook constructs a new instance of type Book
func NewBook(name string) *Book {
	return &Book{
		name: name,
	}
}

// Name gets the value of field name
func (b *Book) Name() string {
	return b.name
}

// Writers gets the value of field writers
func (b *Book) Writers() []string {
	return b.writers
}

// Owner gets the value of field owner
func (b *Book) Owner() *User {
	return b.owner
}

// SetName sets the value of field name
func (b *Book) SetName(name_ string) {
	b.name = name_
}

// SetWriters sets the value of field writers
func (b *Book) SetWriters(writers_ []string) {
	b.writers = writers_
}

// SetOwner sets the value of field owner
func (b *Book) SetOwner(owner_ *User) {
	b.owner = owner_
}

type _Book_marshal struct {
	Name    string   `json:"name"`
	Writers []string `json:"writers"`
	Owner   *User    `json:"owner"`

	Remarks string `json:"Remarks"`
}
type _Book_unmarshal struct {
	Name    string   `json:"name"`
	Writers []string `json:"writers"`
	Owner   *User    `json:"owner"`

	Remarks string `json:"Remarks"`
}

// MarshalJSON serializes type Book to json bytes
func (b Book) MarshalJSON() ([]byte, error) {
	data := _Book_marshal{
		Name:    b.Name(),
		Writers: b.Writers(),
		Owner:   b.Owner(),

		Remarks: b.Remarks,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Book
func (b *Book) UnmarshalJSON(data []byte) error {
	var book_ _Book_unmarshal
	if err := json.Unmarshal(data, &book_); err != nil {
		return err
	}
	b.SetName(book_.Name)
	b.SetWriters(book_.Writers)
	b.SetOwner(book_.Owner)

	b.Remarks = book_.Remarks

	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (b Book) ShootNew() { /*noop*/ }
