// Code generated by "shoot enum -bit -type=Enum"; DO NOT EDIT.

package formatstyleenum

// Has checks if a specific flag is present in the Enum set.
func (e Enum) Has(flag Enum) bool {
	return e&flag == flag
}

// Add adds a flag to the Enum set.
func (e Enum) Add(flag Enum) Enum {
	return e | flag
}

// Remove removes a flag from the Enum set.
func (e Enum) Remove(flag Enum) Enum {
	return e &^ flag
}
