// Code generated by "shoot new -getset -file=types.go -ver=v0.0.0"; DO NOT EDIT. (v0.0.0)

package shoot

import (
	"go/ast"
	"go/types"

	"golang.org/x/tools/go/packages"
)

// NewValue constructs a new instance of type Value
func NewValue(originalName string, name string, value uint64, signed bool, str string) *Value {
	return &Value{
		originalName: originalName,
		name:         name,
		value:        value,
		signed:       signed,
		str:          str,
	}
}

// OriginalName gets the value of field originalName
func (v *Value) OriginalName() string {
	return v.originalName
}

// Name gets the value of field name
func (v *Value) Name() string {
	return v.name
}

// Value gets the value of field value
func (v *Value) Value() uint64 {
	return v.value
}

// Signed gets the value of field signed
func (v *Value) Signed() bool {
	return v.signed
}

// Str gets the value of field str
func (v *Value) Str() string {
	return v.str
}

// SetOriginalName sets the value of field originalName
func (v *Value) SetOriginalName(originalName_ string) {
	v.originalName = originalName_
}

// SetName sets the value of field name
func (v *Value) SetName(name_ string) {
	v.name = name_
}

// SetValue sets the value of field value
func (v *Value) SetValue(value_ uint64) {
	v.value = value_
}

// SetSigned sets the value of field signed
func (v *Value) SetSigned(signed_ bool) {
	v.signed = signed_
}

// SetStr sets the value of field str
func (v *Value) SetStr(str_ string) {
	v.str = str_
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (v Value) ShootNew() { /*noop*/ }

// ValueGetter is read-only interface for Value type
type ValueGetter interface {
	OriginalName() string
	Name() string
	Value() uint64
	Signed() bool
	Str() string
}

// ValueSetter is write-only interface for Value type
type ValueSetter interface {
	SetOriginalName(string)
	SetName(string)
	SetValue(uint64)
	SetSigned(bool)
	SetStr(string)
}

// NewFile constructs a new instance of type File
func NewFile(pkg *Package, file *ast.File, typeName string, values []Value, trimPrefix string, lineComment bool) *File {
	return &File{
		pkg:         pkg,
		file:        file,
		typeName:    typeName,
		values:      values,
		trimPrefix:  trimPrefix,
		lineComment: lineComment,
	}
}

// Pkg gets the value of field pkg
func (f *File) Pkg() *Package {
	return f.pkg
}

// File gets the value of field file
func (f *File) File() *ast.File {
	return f.file
}

// TypeName gets the value of field typeName
func (f *File) TypeName() string {
	return f.typeName
}

// Values gets the value of field values
func (f *File) Values() []Value {
	return f.values
}

// TrimPrefix gets the value of field trimPrefix
func (f *File) TrimPrefix() string {
	return f.trimPrefix
}

// LineComment gets the value of field lineComment
func (f *File) LineComment() bool {
	return f.lineComment
}

// SetPkg sets the value of field pkg
func (f *File) SetPkg(pkg_ *Package) {
	f.pkg = pkg_
}

// SetFile sets the value of field file
func (f *File) SetFile(file_ *ast.File) {
	f.file = file_
}

// SetTypeName sets the value of field typeName
func (f *File) SetTypeName(typeName_ string) {
	f.typeName = typeName_
}

// SetValues sets the value of field values
func (f *File) SetValues(values_ []Value) {
	f.values = values_
}

// SetTrimPrefix sets the value of field trimPrefix
func (f *File) SetTrimPrefix(trimPrefix_ string) {
	f.trimPrefix = trimPrefix_
}

// SetLineComment sets the value of field lineComment
func (f *File) SetLineComment(lineComment_ bool) {
	f.lineComment = lineComment_
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (f File) ShootNew() { /*noop*/ }

// FileGetter is read-only interface for File type
type FileGetter interface {
	Pkg() *Package
	File() *ast.File
	TypeName() string
	Values() []Value
	TrimPrefix() string
	LineComment() bool
}

// FileSetter is write-only interface for File type
type FileSetter interface {
	SetPkg(*Package)
	SetFile(*ast.File)
	SetTypeName(string)
	SetValues([]Value)
	SetTrimPrefix(string)
	SetLineComment(bool)
}

// NewPackage constructs a new instance of type Package
func NewPackage(pkg *packages.Package, dir string, name string, defs map[*ast.Ident]types.Object, files []*File, typesPkg *types.Package) *Package {
	return &Package{
		pkg:      pkg,
		dir:      dir,
		name:     name,
		defs:     defs,
		files:    files,
		typesPkg: typesPkg,
	}
}

// Pkg gets the value of field pkg
func (p *Package) Pkg() *packages.Package {
	return p.pkg
}

// Dir gets the value of field dir
func (p *Package) Dir() string {
	return p.dir
}

// Name gets the value of field name
func (p *Package) Name() string {
	return p.name
}

// Defs gets the value of field defs
func (p *Package) Defs() map[*ast.Ident]types.Object {
	return p.defs
}

// Files gets the value of field files
func (p *Package) Files() []*File {
	return p.files
}

// TypesPkg gets the value of field typesPkg
func (p *Package) TypesPkg() *types.Package {
	return p.typesPkg
}

// SetPkg sets the value of field pkg
func (p *Package) SetPkg(pkg_ *packages.Package) {
	p.pkg = pkg_
}

// SetDir sets the value of field dir
func (p *Package) SetDir(dir_ string) {
	p.dir = dir_
}

// SetName sets the value of field name
func (p *Package) SetName(name_ string) {
	p.name = name_
}

// SetDefs sets the value of field defs
func (p *Package) SetDefs(defs_ map[*ast.Ident]types.Object) {
	p.defs = defs_
}

// SetFiles sets the value of field files
func (p *Package) SetFiles(files_ []*File) {
	p.files = files_
}

// SetTypesPkg sets the value of field typesPkg
func (p *Package) SetTypesPkg(typesPkg_ *types.Package) {
	p.typesPkg = typesPkg_
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (p Package) ShootNew() { /*noop*/ }

// PackageGetter is read-only interface for Package type
type PackageGetter interface {
	Pkg() *packages.Package
	Dir() string
	Name() string
	Defs() map[*ast.Ident]types.Object
	Files() []*File
	TypesPkg() *types.Package
}

// PackageSetter is write-only interface for Package type
type PackageSetter interface {
	SetPkg(*packages.Package)
	SetDir(string)
	SetName(string)
	SetDefs(map[*ast.Ident]types.Object)
	SetFiles([]*File)
	SetTypesPkg(*types.Package)
}
