// Code generated by "shoot rest -type=Client"; DO NOT EDIT. (v0.7.0-beta.2)

package myclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"time"

	"github.com/lopolopen/shoot"
)

type client struct {
	client *http.Client
	conf   *shoot.RestConf
}

func (c *client) Get(ctx context.Context, key string) (*KV, *http.Response, error) {
	path_ := "/get"

	url_, err := url.JoinPath(c.conf.BaseURL(), path_)
	if err != nil {
		return nil, nil, err
	}

	req_, err := http.NewRequestWithContext(ctx, "GET", url_, nil)
	if err != nil {
		return nil, nil, err
	}

	query_ := req_.URL.Query()
	query_.Set("key", fmt.Sprintf("%v", key))
	req_.URL.RawQuery = query_.Encode()

	req_.Header.Add("Accept", "application/json")
	req_.Header.Add("Authorization", "Basic dXNlcm5hbWU6cGFzc3dvcmQ=")

	resp_, err := c.client.Do(req_)
	if err != nil {
		return nil, nil, err
	}
	defer resp_.Body.Close()

	switch {
	case resp_.StatusCode >= 500:
		body_, _ := io.ReadAll(resp_.Body)
		err = fmt.Errorf("server error %d: %s", resp_.StatusCode, string(body_))
	case resp_.StatusCode >= 400:
		body_, _ := io.ReadAll(resp_.Body)
		err = fmt.Errorf("client error %d: %s", resp_.StatusCode, string(body_))
	case resp_.StatusCode >= 300 || resp_.StatusCode < 200:
		err = fmt.Errorf("not supported error %d", resp_.StatusCode)
	}
	if err != nil {
		return nil, resp_, err
	}

	var r_ KV
	err = json.NewDecoder(resp_.Body).Decode(&r_)
	if err == io.EOF {
		err = nil //ignore EOF errors caused by empty response body
	}
	if err != nil {
		return nil, resp_, err
	}
	return &r_, resp_, nil
}

func (c *client) Set(ctx context.Context, kv *KV) (*http.Response, error) {
	path_ := "/set"

	url_, err := url.JoinPath(c.conf.BaseURL(), path_)
	if err != nil {
		return nil, err
	}

	bodyJson_, err := json.Marshal(kv)
	if err != nil {
		return nil, err
	}

	req_, err := http.NewRequestWithContext(ctx, "POST", url_, bytes.NewReader(bodyJson_))
	if err != nil {
		return nil, err
	}

	req_.Header.Add("Accept", "application/json")
	req_.Header.Add("Authorization", "Basic dXNlcm5hbWU6cGFzc3dvcmQ=")
	req_.Header.Add("Content-Type", "application/json")

	resp_, err := c.client.Do(req_)
	if err != nil {
		return nil, err
	}
	defer resp_.Body.Close()

	switch {
	case resp_.StatusCode >= 500:
		body_, _ := io.ReadAll(resp_.Body)
		err = fmt.Errorf("server error %d: %s", resp_.StatusCode, string(body_))
	case resp_.StatusCode >= 400:
		body_, _ := io.ReadAll(resp_.Body)
		err = fmt.Errorf("client error %d: %s", resp_.StatusCode, string(body_))
	case resp_.StatusCode >= 300 || resp_.StatusCode < 200:
		err = fmt.Errorf("not supported error %d", resp_.StatusCode)
	}
	if err != nil {
		return resp_, err
	}
	return resp_, nil
}

// ConfigHTTPClient allows customization of the underlying http.Client.
func (c *client) ConfigHTTPClient(config func(*http.Client)) Client {
	config(c.client)
	return c
}

// ShootRest exists solely to fulfill the RestShooter interface contract.
func (c *client) ShootRest() { /*noop*/ }

func init() {
	shoot.Register(func(conf shoot.RestConf) Client {
		return &client{
			conf: &conf,
			client: &http.Client{
				Timeout:   time.Duration(conf.Timeout()) * time.Second,
				Transport: conf.BuildMiddleware(),
			},
		}
	})
}
