// Code generated by "shoot new -getset -json -file=client.go"; DO NOT EDIT. (v0.7.0-beta.2)

package myclient

import "encoding/json"

// NewKV constructs a new instance of type KV
func NewKV(key string, value string) *KV {
	return &KV{
		key:   key,
		value: value,
	}
}

// Key gets the value of field key
func (k *KV) Key() string {
	return k.key
}

// Value gets the value of field value
func (k *KV) Value() string {
	return k.value
}

// SetKey sets the value of field key
func (k *KV) SetKey(key_ string) {
	k.key = key_
}

// SetValue sets the value of field value
func (k *KV) SetValue(value_ string) {
	k.value = value_
}

type _json_KV struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// MarshalJSON serializes type KV to json bytes
func (k KV) MarshalJSON() ([]byte, error) {
	data := _json_KV{
		Key:   k.Key(),
		Value: k.Value(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type KV
func (k *KV) UnmarshalJSON(data []byte) error {
	var kv_ _json_KV
	if err := json.Unmarshal(data, &kv_); err != nil {
		return err
	}
	k.SetKey(kv_.Key)
	k.SetValue(kv_.Value)
	return nil
}

// KVGetter is read-only interface for KV type
type KVGetter interface {
	Key() string
	Value() string
}

// KVSetter is write-only interface for KV type
type KVSetter interface {
	SetKey(string)
	SetValue(string)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (k KV) ShootNew() { /*noop*/ }
