// Code generated by "shoot new -getset -json -file=resp.go"; DO NOT EDIT. (v0.7.0-beta.2)

package model

import "encoding/json"

// NewPageResult constructs a new instance of type PageResult
func NewPageResult(perPage int, page int, totalPage int) *PageResult {
	return &PageResult{
		perPage:   perPage,
		page:      page,
		totalPage: totalPage,
	}
}

// PerPage gets the value of field perPage
func (p *PageResult) PerPage() int {
	return p.perPage
}

// Page gets the value of field page
func (p *PageResult) Page() int {
	return p.page
}

// TotalPage gets the value of field totalPage
func (p *PageResult) TotalPage() int {
	return p.totalPage
}

// SetPerPage sets the value of field perPage
func (p *PageResult) SetPerPage(perPage_ int) {
	p.perPage = perPage_
}

// SetPage sets the value of field page
func (p *PageResult) SetPage(page_ int) {
	p.page = page_
}

// SetTotalPage sets the value of field totalPage
func (p *PageResult) SetTotalPage(totalPage_ int) {
	p.totalPage = totalPage_
}

type _json_PageResult struct {
	PerPage   int `json:"perPage"`
	Page      int `json:"page"`
	TotalPage int `json:"totalPage"`
}

// MarshalJSON serializes type PageResult to json bytes
func (p PageResult) MarshalJSON() ([]byte, error) {
	data := _json_PageResult{
		PerPage:   p.PerPage(),
		Page:      p.Page(),
		TotalPage: p.TotalPage(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type PageResult
func (p *PageResult) UnmarshalJSON(data []byte) error {
	var pageResult_ _json_PageResult
	if err := json.Unmarshal(data, &pageResult_); err != nil {
		return err
	}
	p.SetPerPage(pageResult_.PerPage)
	p.SetPage(pageResult_.Page)
	p.SetTotalPage(pageResult_.TotalPage)
	return nil
}

// PageResultGetter is read-only interface for PageResult type
type PageResultGetter interface {
	PerPage() int
	Page() int
	TotalPage() int
}

// PageResultSetter is write-only interface for PageResult type
type PageResultSetter interface {
	SetPerPage(int)
	SetPage(int)
	SetTotalPage(int)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (p PageResult) ShootNew() { /*noop*/ }

// NewResp constructs a new instance of type Resp
func NewResp(code int, msg string, perPage int, page int, totalPage int) *Resp {
	return &Resp{
		code: code,
		msg:  msg,
		PageResult: &PageResult{
			perPage:   perPage,
			page:      page,
			totalPage: totalPage,
		},
	}
}

// Code gets the value of field code
func (r *Resp) Code() int {
	return r.code
}

// Msg gets the value of field msg
func (r *Resp) Msg() string {
	return r.msg
}

// SetCode sets the value of field code
func (r *Resp) SetCode(code_ int) {
	r.code = code_
}

// SetMsg sets the value of field msg
func (r *Resp) SetMsg(msg_ string) {
	r.msg = msg_
}

type _json_Resp struct {
	Code      int    `json:"code"`
	Msg       string `json:"msg"`
	PerPage   int    `json:"perPage"`
	Page      int    `json:"page"`
	TotalPage int    `json:"totalPage"`
}

// MarshalJSON serializes type Resp to json bytes
func (r Resp) MarshalJSON() ([]byte, error) {
	data := _json_Resp{
		Code:      r.Code(),
		Msg:       r.Msg(),
		PerPage:   r.PerPage(),
		Page:      r.Page(),
		TotalPage: r.TotalPage(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Resp
func (r *Resp) UnmarshalJSON(data []byte) error {
	var resp_ _json_Resp
	if err := json.Unmarshal(data, &resp_); err != nil {
		return err
	}
	r.SetCode(resp_.Code)
	r.SetMsg(resp_.Msg)
	r.SetPerPage(resp_.PerPage)
	r.SetPage(resp_.Page)
	r.SetTotalPage(resp_.TotalPage)
	return nil
}

// RespGetter is read-only interface for Resp type
type RespGetter interface {
	PageResultGetter
	Code() int
	Msg() string
}

// RespSetter is write-only interface for Resp type
type RespSetter interface {
	PageResultSetter
	SetCode(int)
	SetMsg(string)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (r Resp) ShootNew() { /*noop*/ }

// NewUserResp constructs a new instance of type UserResp
func NewUserResp(code int, msg string, perPage int, page int, totalPage int, data *User) *UserResp {
	return &UserResp{
		Resp: Resp{
			code: code,
			msg:  msg,
			PageResult: &PageResult{
				perPage:   perPage,
				page:      page,
				totalPage: totalPage,
			},
		},
		data: data,
	}
}

// Data gets the value of field data
func (u *UserResp) Data() *User {
	return u.data
}

// SetData sets the value of field data
func (u *UserResp) SetData(data_ *User) {
	u.data = data_
}

type _json_UserResp struct {
	Code      int    `json:"code"`
	Msg       string `json:"msg"`
	PerPage   int    `json:"perPage"`
	Page      int    `json:"page"`
	TotalPage int    `json:"totalPage"`
	Data      *User  `json:"data"`
}

// MarshalJSON serializes type UserResp to json bytes
func (u UserResp) MarshalJSON() ([]byte, error) {
	data := _json_UserResp{
		Code:      u.Code(),
		Msg:       u.Msg(),
		PerPage:   u.PerPage(),
		Page:      u.Page(),
		TotalPage: u.TotalPage(),
		Data:      u.Data(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type UserResp
func (u *UserResp) UnmarshalJSON(data []byte) error {
	var userResp_ _json_UserResp
	if err := json.Unmarshal(data, &userResp_); err != nil {
		return err
	}
	u.SetCode(userResp_.Code)
	u.SetMsg(userResp_.Msg)
	u.SetPerPage(userResp_.PerPage)
	u.SetPage(userResp_.Page)
	u.SetTotalPage(userResp_.TotalPage)
	u.SetData(userResp_.Data)
	return nil
}

// UserRespGetter is read-only interface for UserResp type
type UserRespGetter interface {
	RespGetter
	PageResultGetter
	Data() *User
}

// UserRespSetter is write-only interface for UserResp type
type UserRespSetter interface {
	RespSetter
	PageResultSetter
	SetData(*User)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (u UserResp) ShootNew() { /*noop*/ }
