// Code generated by "shoot enum -file=enums.go"; DO NOT EDIT.

package enum

import "fmt"

func _() {
	var x [1]struct{}
	_ = x[LightRed-0]
	_ = x[LightYello-1]
	_ = x[LightGreen-2]

}

var _light_values = []Light{
	LightRed,
	LightYello,
	LightGreen,
}

const _light_all = 0 | LightRed | LightYello | LightGreen

var _light_map = map[Light]string{
	LightRed:   "Red",
	LightYello: "Yello",
	LightGreen: "Green",
}

// String returns the string value of type Light
func (l Light) String() string {
	str, ok := _light_map[l]
	if ok {
		return str
	}
	if l < 0 || l > _light_all {
		return fmt.Sprintf("%d", l)
	}

	return fmt.Sprintf("%d", l)
}
