// Code generated by "shoot map -path=../../domain/model -alias=domain -type=Order,User,UserAddress"; DO NOT EDIT. (v0.7.0-beta.2)

package po

import (
	domain "mapperexample/domain/model"

	"gorm.io/gorm"
)

// ToDomain converts receiver to type domain.User
func (u *User) ToDomain() *domain.User {
	if u == nil {
		return nil
	}
	user_ := new(domain.User)
	if u.Model != nil {
		user_.ID = u.ID
	}
	user_.FirstName = u.FirstName
	user_.LastName = u.LastName
	user_.Email = u.Email
	if u.AddressList != nil {
		_ys := make([]*domain.UserAddress, len(u.AddressList))
		for _i, _x := range u.AddressList {
			_ys[_i] = _x.ToDomain()
		}
		user_.AddressList = _ys
	}
	u.writeDomain(user_)
	return user_
}

// FromDomain reads from type domain.User, then writes back to receiver and returns it
func (u *User) FromDomain(user_ *domain.User) *User {
	if user_ == nil {
		return nil
	}
	if u == nil {
		u = new(User)
	} else {
		*u = User{}
	}
	if u.Model == nil {
		u.Model = new(gorm.Model)
	}
	u.ID = user_.ID
	u.FirstName = user_.FirstName
	u.LastName = user_.LastName
	u.Email = user_.Email
	if user_.AddressList != nil {
		_ys := make([]*UserAddress, len(user_.AddressList))
		for _i, _x := range user_.AddressList {
			_ys[_i] = new(UserAddress).FromDomain(_x)
		}
		u.AddressList = _ys
	}
	u.readDomain(*user_)
	return u
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (u User) ShootMap() { /*noop*/ }
