// Code generated by "shoot map -path=../../domain/model2 -alias=domain -type=Order -v"; DO NOT EDIT. (v0.3.3-beta.1)

package dto2

import domain "mappersample/domain/model2"

// ToDomain converts receiver to type domain.Order
func (o *Order) ToDomain() *domain.Order {
	if o == nil {
		return nil
	}
	order_ := new(domain.Order)
	if o.AddrList2 != nil {
		order_AddrList2 := make([]*domain.OrderAddress, len(o.AddrList2))
		for _i, _x := range o.AddrList2 {
			order_AddrList2[_i] = _x.ToDomain()
		}
		order_.AddrList2 = order_AddrList2
	}
	order_.X = o.X
	order_.SetId(o.Id())
	order_.SetAmount(o.StringToDecimal(o.Amount()))
	order_.SetStatus(o.Status())
	order_.SetOrderTime(o.StringToTime(o.OrderingTime()))
	if o.Address() != nil {
		order_.SetAddress(*o.Address().ToDomain())
	}
	oAddress2 := o.Address2()
	order_.SetAddress2(*oAddress2.ToDomain())
	if o.AddrList() != nil {
		order_SetAddrList := make([]*domain.OrderAddress, len(o.AddrList()))
		for _i, _x := range o.AddrList() {
			order_SetAddrList[_i] = _x.ToDomain()
		}
		order_.SetAddrList(order_SetAddrList)
	}
	o.writeDomain(order_)
	return order_
}

// FromDomain reads from type domain.Order, then writes back to receiver and returns it
func (o *Order) FromDomain(order_ *domain.Order) *Order {
	if order_ == nil {
		return o
	}
	if o == nil {
		o = new(Order)
	}
	if order_.AddrList2 != nil {
		oAddrList2 := make([]*OrderAddress, len(order_.AddrList2))
		for _i, _x := range order_.AddrList2 {
			oAddrList2[_i] = new(OrderAddress).FromDomain(_x)
		}
		o.AddrList2 = oAddrList2
	}
	o.X = order_.X
	o.SetId(order_.Id())
	o.SetAmount(o.DecimalToString(order_.Amount()))
	o.SetStatus(order_.Status())
	o.SetOrderingTime(o.TimeToString(order_.OrderTime()))
	order_Address := order_.Address()
	o.SetAddress(new(OrderAddress).FromDomain(&order_Address))
	order_Address2 := order_.Address2()
	o.SetAddress2(*new(OrderAddress).FromDomain(&order_Address2))
	if order_.AddrList() != nil {
		oSetAddrList := make([]*OrderAddress, len(order_.AddrList()))
		for _i, _x := range order_.AddrList() {
			oSetAddrList[_i] = new(OrderAddress).FromDomain(_x)
		}
		o.SetAddrList(oSetAddrList)
	}
	o.readDomain(order_)
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o Order) ShootMap() { /*noop*/ }
