// Code generated by "shoot map -path=../../domain/model2 -alias=domain -type=OrderAddress"; DO NOT EDIT. (v0.3.3-beta.1)

package dto2

import domain "mappersample/domain/model2"

// ToDomain converts receiver to type domain.OrderAddress
func (o *OrderAddress) ToDomain() *domain.OrderAddress {
	if o == nil {
		return nil
	}
	orderAddress_ := new(domain.OrderAddress)
	orderAddress_.SetCity(o.City())
	orderAddress_.SetStreet(o.Street())
	orderAddress_.SetRoom(o.RoomNum())
	o.writeDomain(orderAddress_)
	return orderAddress_
}

// FromDomain reads from type domain.OrderAddress, then writes back to receiver and returns it
func (o *OrderAddress) FromDomain(orderAddress_ *domain.OrderAddress) *OrderAddress {
	if orderAddress_ == nil {
		return o
	}
	if o == nil {
		o = new(OrderAddress)
	}
	o.SetCity(orderAddress_.City())
	o.SetStreet(orderAddress_.Street())
	o.SetRoomNum(orderAddress_.Room())
	o.readDomain(orderAddress_)
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o OrderAddress) ShootMap() { /*noop*/ }
