// Code generated by "shoot new -getset -json -type=OrderAddress"; DO NOT EDIT. (v0.3.2-beta.5)

package dto2

import "encoding/json"

// NewOrderAddress constructs a new instance of type OrderAddress
func NewOrderAddress(city string, street string, roomNum string) *OrderAddress {
	return &OrderAddress{
		city:    city,
		street:  street,
		roomNum: roomNum,
	}
}

// City gets the value of field city
func (o *OrderAddress) City() string {
	return o.city
}

// Street gets the value of field street
func (o *OrderAddress) Street() string {
	return o.street
}

// RoomNum gets the value of field roomNum
func (o *OrderAddress) RoomNum() string {
	return o.roomNum
}

// SetCity sets the value of field city
func (o *OrderAddress) SetCity(city_ string) {
	o.city = city_
}

// SetStreet sets the value of field street
func (o *OrderAddress) SetStreet(street_ string) {
	o.street = street_
}

// SetRoomNum sets the value of field roomNum
func (o *OrderAddress) SetRoomNum(roomNum_ string) {
	o.roomNum = roomNum_
}

type _OrderAddress_marshal struct {
	City    string `json:"city"`
	Street  string `json:"street"`
	RoomNum string
}

type _OrderAddress_unmarshal struct {
	City    string `json:"city"`
	Street  string `json:"street"`
	RoomNum string
}

// MarshalJSON serializes type OrderAddress to json bytes
func (o OrderAddress) MarshalJSON() ([]byte, error) {
	data := _OrderAddress_marshal{
		City:    o.City(),
		Street:  o.Street(),
		RoomNum: o.RoomNum(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type OrderAddress
func (o *OrderAddress) UnmarshalJSON(data []byte) error {
	var orderAddress_ _OrderAddress_unmarshal
	if err := json.Unmarshal(data, &orderAddress_); err != nil {
		return err
	}
	o.SetCity(orderAddress_.City)
	o.SetStreet(orderAddress_.Street)
	o.SetRoomNum(orderAddress_.RoomNum)
	return nil
}

// OrderAddressGetter is read-only interface for OrderAddress type
type OrderAddressGetter interface {
	City() string
	Street() string
	RoomNum() string
}

// OrderAddressSetter is write-only interface for OrderAddress type
type OrderAddressSetter interface {
	SetCity(string)
	SetStreet(string)
	SetRoomNum(string)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o OrderAddress) ShootNew() { /*noop*/ }
