// Code generated by "shoot new -getset -json -type=Order"; DO NOT EDIT. (v0.3.3-beta.1)

package dto2

import (
	"encoding/json"
	"mappersample/domain/enums"
)

// NewOrder constructs a new instance of type Order
func NewOrder(id string, amount string, status enums.OrderStatus, orderingTime string, address *OrderAddress, address2 OrderAddress, addrList []*OrderAddress) *Order {
	return &Order{
		id:           id,
		amount:       amount,
		status:       status,
		orderingTime: orderingTime,
		address:      address,
		address2:     address2,
		addrList:     addrList,
	}
}

// Id gets the value of field id
func (o *Order) Id() string {
	return o.id
}

// Amount gets the value of field amount
func (o *Order) Amount() string {
	return o.amount
}

// Status gets the value of field status
func (o *Order) Status() enums.OrderStatus {
	return o.status
}

// OrderingTime gets the value of field orderingTime
func (o *Order) OrderingTime() string {
	return o.orderingTime
}

// Address gets the value of field address
func (o *Order) Address() *OrderAddress {
	return o.address
}

// Address2 gets the value of field address2
func (o *Order) Address2() OrderAddress {
	return o.address2
}

// AddrList gets the value of field addrList
func (o *Order) AddrList() []*OrderAddress {
	return o.addrList
}

// SetId sets the value of field id
func (o *Order) SetId(id_ string) {
	o.id = id_
}

// SetAmount sets the value of field amount
func (o *Order) SetAmount(amount_ string) {
	o.amount = amount_
}

// SetStatus sets the value of field status
func (o *Order) SetStatus(status_ enums.OrderStatus) {
	o.status = status_
}

// SetOrderingTime sets the value of field orderingTime
func (o *Order) SetOrderingTime(orderingTime_ string) {
	o.orderingTime = orderingTime_
}

// SetAddress sets the value of field address
func (o *Order) SetAddress(address_ *OrderAddress) {
	o.address = address_
}

// SetAddress2 sets the value of field address2
func (o *Order) SetAddress2(address2_ OrderAddress) {
	o.address2 = address2_
}

// SetAddrList sets the value of field addrList
func (o *Order) SetAddrList(addrList_ []*OrderAddress) {
	o.addrList = addrList_
}

type _Order_marshal struct {
	Id           string            `json:"id"`
	Amount       string            `json:"amount"`
	Status       enums.OrderStatus `json:"status"`
	OrderingTime string
	Address      *OrderAddress   `json:"address"`
	Address2     OrderAddress    `json:"address2"`
	AddrList     []*OrderAddress `json:"addrList"`
	AddrList2    []*OrderAddress `json:"AddrList2"`
	X            int             `json:"X"`
}

type _Order_unmarshal struct {
	Id           string            `json:"id"`
	Amount       string            `json:"amount"`
	Status       enums.OrderStatus `json:"status"`
	OrderingTime string
	Address      *OrderAddress   `json:"address"`
	Address2     OrderAddress    `json:"address2"`
	AddrList     []*OrderAddress `json:"addrList"`
	AddrList2    []*OrderAddress `json:"AddrList2"`
	X            int             `json:"X"`
}

// MarshalJSON serializes type Order to json bytes
func (o Order) MarshalJSON() ([]byte, error) {
	data := _Order_marshal{
		Id:           o.Id(),
		Amount:       o.Amount(),
		Status:       o.Status(),
		OrderingTime: o.OrderingTime(),
		Address:      o.Address(),
		Address2:     o.Address2(),
		AddrList:     o.AddrList(),
		AddrList2:    o.AddrList2,
		X:            o.X,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Order
func (o *Order) UnmarshalJSON(data []byte) error {
	var order_ _Order_unmarshal
	if err := json.Unmarshal(data, &order_); err != nil {
		return err
	}
	o.SetId(order_.Id)
	o.SetAmount(order_.Amount)
	o.SetStatus(order_.Status)
	o.SetOrderingTime(order_.OrderingTime)
	o.SetAddress(order_.Address)
	o.SetAddress2(order_.Address2)
	o.SetAddrList(order_.AddrList)
	o.AddrList2 = order_.AddrList2
	o.X = order_.X
	return nil
}

// OrderGetter is read-only interface for Order type
type OrderGetter interface {
	Id() string
	Amount() string
	Status() enums.OrderStatus
	OrderingTime() string
	Address() *OrderAddress
	Address2() OrderAddress
	AddrList() []*OrderAddress
}

// OrderSetter is write-only interface for Order type
type OrderSetter interface {
	SetId(string)
	SetAmount(string)
	SetStatus(enums.OrderStatus)
	SetOrderingTime(string)
	SetAddress(*OrderAddress)
	SetAddress2(OrderAddress)
	SetAddrList([]*OrderAddress)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Order) ShootNew() { /*noop*/ }
