// Code generated by "shoot map -path=./dest -type=Order"; DO NOT EDIT.

package mapper

import "mappersample/mapper/dest"

// ToDest converts receiver to type dest.Order
func (o *Order) ToDest() *dest.Order {
	if o == nil {
		return nil
	}
	order_ := new(dest.Order)
	order_.ID = o.ID
	return order_
}

// FromDest reads from type dest.Order, then writes back to receiver and returns it
func (o *Order) FromDest(order_ *dest.Order) *Order {
	if order_ == nil {
		return o
	}
	if o == nil {
		o = new(Order)
	}
	o.ID = order_.ID
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o Order) ShootMap() { /*noop*/ }
