// Code generated by "shoot map -path=../dest -type=Data"; DO NOT EDIT. (v0.6.1-beta.4)

package src

import (
	"github.com/lopolopen/shoot/samples/mapper-sample3/dest"
	"github.com/lopolopen/shoot/samples/mapper-sample3/iface"
)

// ToDest converts receiver to type dest.Data
func (d *Data) ToDest() *dest.Data {
	if d == nil {
		return nil
	}
	data_ := new(dest.Data)
	data_.X = iface.AIface(d.X)
	data_.Y = iface.AIface(d.Y)
	data_.Age = d.IntToInt32(d.Age)
	return data_
}

// FromDest reads from type dest.Data, then writes back to receiver and returns it
func (d *Data) FromDest(data_ *dest.Data) *Data {
	if data_ == nil {
		return nil
	}
	if d == nil {
		d = new(Data)
	} else {
		*d = Data{}
	}
	d.Age = int(data_.Age)
	return d
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (d Data) ShootMap() { /*noop*/ }
