// Code generated by "shoot rest -type=Client"; DO NOT EDIT.

package xclient

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"restclientsample/xclient/dto"
	"time"

	"github.com/lopolopen/shoot"
)

type client struct {
	client *http.Client
	conf   *shoot.RestConf
}

func (c *client) QueryBooks0(ctx context.Context, req QueryBooksReq) (*dto.QueryBooksResp, error) {
	path_ := "/books"

	url_, err := url.JoinPath(c.conf.BaseURL(), path_)
	if err != nil {
		return nil, err
	}

	req_, err := http.NewRequestWithContext(ctx, "GET", url_, nil)
	if err != nil {
		return nil, err
	}

	query_ := req_.URL.Query()
	query_.Set("name", fmt.Sprintf("%v", req.Name()))
	query_.Set("lang", fmt.Sprintf("%v", req.Language()))
	query_.Set("page_size", fmt.Sprintf("%v", req.PageSize))
	query_.Set("pageIndex", fmt.Sprintf("%v", req.PageIndex))
	req_.URL.RawQuery = query_.Encode()

	req_.Header.Add("Accept", "application/json")
	req_.Header.Add("Tenant-Id", "123")

	resp_, err := c.client.Do(req_)
	if err != nil {
		return nil, err
	}
	defer resp_.Body.Close()

	body_, err := io.ReadAll(resp_.Body)
	if err != nil {
		return nil, err
	}
	var result_ dto.QueryBooksResp
	err = json.Unmarshal(body_, &result_)
	if err != nil {
		return nil, err
	}
	return &result_, nil
}

// ConfigHTTPClient allows customization of the underlying http.Client.
func (c *client) ConfigHTTPClient(config func(*http.Client)) Client {
	config(c.client)
	return c
}

// ShootRest exists solely to fulfill the RestShooter interface contract.
func (c *client) ShootRest() { /*noop*/ }

func init() {
	shoot.Register(func(conf shoot.RestConf) Client {
		return &client{
			conf: &conf,
			client: &http.Client{
				Timeout:   time.Duration(conf.Timeout()) * time.Second,
				Transport: conf.BuildMiddleware(),
			},
		}
	})
}
