// Code generated by "shoot new -getset -json -file=client.go"; DO NOT EDIT.

package xclient

import "encoding/json"

// NewUser constructs a new instance of type User
func NewUser(id string, name string, age int, gender Gender) *User {
	return &User{
		id:     id,
		name:   name,
		age:    age,
		gender: gender,
	}
}

// Id gets the value of field id
func (u *User) Id() string {
	return u.id
}

// Name gets the value of field name
func (u *User) Name() string {
	return u.name
}

// Age gets the value of field age
func (u *User) Age() int {
	return u.age
}

// Gender gets the value of field gender
func (u *User) Gender() Gender {
	return u.gender
}

// SetId sets the value of field id
func (u *User) SetId(id_ string) {
	u.id = id_
}

// SetName sets the value of field name
func (u *User) SetName(name_ string) {
	u.name = name_
}

// SetAge sets the value of field age
func (u *User) SetAge(age_ int) {
	u.age = age_
}

// SetGender sets the value of field gender
func (u *User) SetGender(gender_ Gender) {
	u.gender = gender_
}

type _User_marshal struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Age    int    `json:"age"`
	Gender Gender `json:"gender"`
}
type _User_unmarshal struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Age    int    `json:"age"`
	Gender Gender `json:"gender"`
}

// MarshalJSON serializes type User to json bytes
func (u User) MarshalJSON() ([]byte, error) {
	data := _User_marshal{
		Id:     u.Id(),
		Name:   u.Name(),
		Age:    u.Age(),
		Gender: u.Gender(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type User
func (u *User) UnmarshalJSON(data []byte) error {
	var user_ _User_unmarshal
	if err := json.Unmarshal(data, &user_); err != nil {
		return err
	}
	u.SetId(user_.Id)
	u.SetName(user_.Name)
	u.SetAge(user_.Age)
	u.SetGender(user_.Gender)

	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (u User) ShootNew() { /*noop*/ }

// NewQueryBooksReq constructs a new instance of type QueryBooksReq
func NewQueryBooksReq(name *string, language string) *QueryBooksReq {
	return &QueryBooksReq{
		name:     name,
		language: language,
	}
}

// Name gets the value of field name
func (q *QueryBooksReq) Name() *string {
	return q.name
}

// Language gets the value of field language
func (q *QueryBooksReq) Language() string {
	return q.language
}

// SetName sets the value of field name
func (q *QueryBooksReq) SetName(name_ *string) {
	q.name = name_
}

// SetLanguage sets the value of field language
func (q *QueryBooksReq) SetLanguage(language_ string) {
	q.language = language_
}

type _QueryBooksReq_marshal struct {
	Name     *string `json:"name"`
	Language string

	PageSize int

	PageIndex *int `json:"PageIndex"`
}
type _QueryBooksReq_unmarshal struct {
	Name     *string `json:"name"`
	Language string

	PageSize  int
	PageIndex *int `json:"PageIndex"`
}

// MarshalJSON serializes type QueryBooksReq to json bytes
func (q QueryBooksReq) MarshalJSON() ([]byte, error) {
	data := _QueryBooksReq_marshal{
		Name:     q.Name(),
		Language: q.Language(),

		PageSize:  q.PageSize,
		PageIndex: q.PageIndex,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type QueryBooksReq
func (q *QueryBooksReq) UnmarshalJSON(data []byte) error {
	var queryBooksReq_ _QueryBooksReq_unmarshal
	if err := json.Unmarshal(data, &queryBooksReq_); err != nil {
		return err
	}
	q.SetName(queryBooksReq_.Name)
	q.SetLanguage(queryBooksReq_.Language)

	q.PageSize = queryBooksReq_.PageSize
	q.PageIndex = queryBooksReq_.PageIndex

	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (q QueryBooksReq) ShootNew() { /*noop*/ }
