// Code generated by "shoot new -getset -type=OrderAddress"; DO NOT EDIT.

package model2

// NewOrderAddress constructs a new instance of type OrderAddress
func NewOrderAddress(city string, street string, room string) *OrderAddress {
	return &OrderAddress{
		city:   city,
		street: street,
		room:   room,
	}
}

// City gets the value of field city
func (o *OrderAddress) City() string {
	return o.city
}

// Street gets the value of field street
func (o *OrderAddress) Street() string {
	return o.street
}

// Room gets the value of field room
func (o *OrderAddress) Room() string {
	return o.room
}

// SetCity sets the value of field city
func (o *OrderAddress) SetCity(city_ string) {
	o.city = city_
}

// SetStreet sets the value of field street
func (o *OrderAddress) SetStreet(street_ string) {
	o.street = street_
}

// SetRoom sets the value of field room
func (o *OrderAddress) SetRoom(room_ string) {
	o.room = room_
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o OrderAddress) ShootNew() { /*noop*/ }

// OrderAddressGetter is read-only interface for OrderAddress type
type OrderAddressGetter interface {
	City() string
	Street() string
	Room() string
}

// OrderAddressSetter is write-only interface for OrderAddress type
type OrderAddressSetter interface {
	SetCity(string)
	SetStreet(string)
	SetRoom(string)
}
