// Code generated by "shoot new -getset -type=Order"; DO NOT EDIT. (v0.3.3-beta.1)

package model2

import (
	"mappersample/domain/enums"
	"time"

	"github.com/shopspring/decimal"
)

// NewOrder constructs a new instance of type Order
func NewOrder(id string, amount decimal.Decimal, status enums.OrderStatus, orderTime time.Time, address OrderAddress, address2 OrderAddress, addrList []*OrderAddress) *Order {
	return &Order{
		id:        id,
		amount:    amount,
		status:    status,
		orderTime: orderTime,
		address:   address,
		address2:  address2,
		addrList:  addrList,
	}
}

// Id gets the value of field id
func (o *Order) Id() string {
	return o.id
}

// Amount gets the value of field amount
func (o *Order) Amount() decimal.Decimal {
	return o.amount
}

// Status gets the value of field status
func (o *Order) Status() enums.OrderStatus {
	return o.status
}

// OrderTime gets the value of field orderTime
func (o *Order) OrderTime() time.Time {
	return o.orderTime
}

// Address gets the value of field address
func (o *Order) Address() OrderAddress {
	return o.address
}

// Address2 gets the value of field address2
func (o *Order) Address2() OrderAddress {
	return o.address2
}

// AddrList gets the value of field addrList
func (o *Order) AddrList() []*OrderAddress {
	return o.addrList
}

// SetId sets the value of field id
func (o *Order) SetId(id_ string) {
	o.id = id_
}

// SetAmount sets the value of field amount
func (o *Order) SetAmount(amount_ decimal.Decimal) {
	o.amount = amount_
}

// SetStatus sets the value of field status
func (o *Order) SetStatus(status_ enums.OrderStatus) {
	o.status = status_
}

// SetOrderTime sets the value of field orderTime
func (o *Order) SetOrderTime(orderTime_ time.Time) {
	o.orderTime = orderTime_
}

// SetAddress sets the value of field address
func (o *Order) SetAddress(address_ OrderAddress) {
	o.address = address_
}

// SetAddress2 sets the value of field address2
func (o *Order) SetAddress2(address2_ OrderAddress) {
	o.address2 = address2_
}

// SetAddrList sets the value of field addrList
func (o *Order) SetAddrList(addrList_ []*OrderAddress) {
	o.addrList = addrList_
}

// OrderGetter is read-only interface for Order type
type OrderGetter interface {
	Id() string
	Amount() decimal.Decimal
	Status() enums.OrderStatus
	OrderTime() time.Time
	Address() OrderAddress
	Address2() OrderAddress
	AddrList() []*OrderAddress
}

// OrderSetter is write-only interface for Order type
type OrderSetter interface {
	SetId(string)
	SetAmount(decimal.Decimal)
	SetStatus(enums.OrderStatus)
	SetOrderTime(time.Time)
	SetAddress(OrderAddress)
	SetAddress2(OrderAddress)
	SetAddrList([]*OrderAddress)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Order) ShootNew() { /*noop*/ }
