// Code generated by "shoot map -path=../../domain/model -alias=domain -type=*"; DO NOT EDIT.

package dto

import domain "mappersample/domain/model"

// ToDomain converts receiver to type domain.Order
func (o *Order) ToDomain() *domain.Order {
	order_ := new(domain.Order)
	order_.ID = o.ID
	order_.Amount = o.StringToDecimal(o.Amount)
	order_.Status = o.Status
	order_.OrderTime = o.StringToTime(o.OrderingTime)
	if o.Address != nil {
		order_.Address = *o.Address.ToDomain()
	}
	order_.Price = domain.Price(o.Price)
	order_.Price2 = o.Price2
	order_.Value = int32(o.Value)
	o.writeDomain(order_)
	return order_
}

// FromDomain read from type domain.Order, then write back to receiver
func (o *Order) FromDomain(order_ *domain.Order) *Order {
	o.ID = order_.ID
	o.Amount = o.DecimalToString(order_.Amount)
	o.Status = order_.Status
	o.OrderingTime = o.TimeToString(order_.OrderTime)
	o.Address = new(OrderAddress).FromDomain(&order_.Address)
	o.Price = domain.Decimal(o.Price)
	o.Price2 = order_.Price2
	o.Value = int(o.Value)
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o Order) ShootMap() { /*noop*/ }

// ToDomain converts receiver to type domain.OrderAddress
func (o *OrderAddress) ToDomain() *domain.OrderAddress {
	orderAddress_ := new(domain.OrderAddress)
	orderAddress_.City = o.City
	orderAddress_.Street = o.Street
	orderAddress_.Room = o.RoomNum
	return orderAddress_
}

// FromDomain read from type domain.OrderAddress, then write back to receiver
func (o *OrderAddress) FromDomain(orderAddress_ *domain.OrderAddress) *OrderAddress {
	o.City = orderAddress_.City
	o.Street = orderAddress_.Street
	o.RoomNum = orderAddress_.Room
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o OrderAddress) ShootMap() { /*noop*/ }

// ToDomain converts receiver to type domain.User
func (u *User) ToDomain() *domain.User {
	user_ := new(domain.User)
	user_.ID = u.ID
	user_.Email = u.Email
	u.toDomain(user_)
	return user_
}

// FromDomain read from type domain.User, then write back to receiver
func (u *User) FromDomain(user_ *domain.User) *User {
	u.ID = user_.ID
	u.Email = user_.Email
	u.fromDomain(*user_)
	return u
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (u User) ShootMap() { /*noop*/ }

// ToDomain converts receiver to type domain.UserAddress
func (u *UserAddress) ToDomain() *domain.UserAddress {
	userAddress_ := new(domain.UserAddress)
	userAddress_.ID = u.ID
	userAddress_.City = u.City
	userAddress_.Street = u.Street
	userAddress_.Room = u.Room
	userAddress_.Tag = u.Tag
	userAddress_.IsDefault = u.IsDefault
	return userAddress_
}

// FromDomain read from type domain.UserAddress, then write back to receiver
func (u *UserAddress) FromDomain(userAddress_ *domain.UserAddress) *UserAddress {
	u.ID = userAddress_.ID
	u.City = userAddress_.City
	u.Street = userAddress_.Street
	u.Room = userAddress_.Room
	u.Tag = userAddress_.Tag
	u.IsDefault = userAddress_.IsDefault
	return u
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (u UserAddress) ShootMap() { /*noop*/ }
