// Code generated by "shoot map -path=../../domain/model -type=*"; DO NOT EDIT.

package dto

import "mappersample/domain/model"
import "github.com/shopspring/decimal"

// ToModel converts receiver to type model.Order
func (o *Order) ToModel() *model.Order {
	order_ := new(model.Order)
	order_.ID = o.ID
	order_.Amount = o.StringToDecimal(o.Amount)
	order_.Status = o.Status
	order_.OrderTime = o.StringToTime(o.OrderingTime)
	order_.Price = model.Price(o.Price)
	order_.Price2 = o.Price2
	order_.Value = int32(o.Value)
	o.writeModel(order_)
	return order_
}

// FromModel read from type model.Order, then write back to receiver
func (o *Order) FromModel(order_ *model.Order) *Order {
	o.ID = order_.ID
	o.Amount = o.DecimalToString(order_.Amount)
	o.Status = order_.Status
	o.OrderingTime = o.TimeToString(order_.OrderTime)
	o.Price = decimal.Decimal(o.Price)
	o.Price2 = order_.Price2
	o.Value = int(o.Value)
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o Order) ShootMap() { /*noop*/ }

// ToModel converts receiver to type model.OrderAddress
func (o *OrderAddress) ToModel() *model.OrderAddress {
	orderAddress_ := new(model.OrderAddress)
	orderAddress_.City = o.City
	orderAddress_.Street = o.Street
	orderAddress_.Room = o.RoomNum
	return orderAddress_
}

// FromModel read from type model.OrderAddress, then write back to receiver
func (o *OrderAddress) FromModel(orderAddress_ *model.OrderAddress) *OrderAddress {
	o.City = orderAddress_.City
	o.Street = orderAddress_.Street
	o.RoomNum = orderAddress_.Room
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o OrderAddress) ShootMap() { /*noop*/ }

// ToModel converts receiver to type model.User
func (u *User) ToModel() *model.User {
	user_ := new(model.User)
	user_.ID = u.ID
	user_.Email = u.Email
	u.toModel(user_)
	return user_
}

// FromModel read from type model.User, then write back to receiver
func (u *User) FromModel(user_ *model.User) *User {
	u.ID = user_.ID
	u.Email = user_.Email
	u.fromModel(*user_)
	return u
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (u User) ShootMap() { /*noop*/ }
