// Code generated by "shoot map -path=../../domain/model -alias=domain -type=Order"; DO NOT EDIT.

package dto

import domain "mappersample/domain/model"

// ToDomain converts receiver to type domain.Order
func (o *Order) ToDomain() *domain.Order {
	if o == nil {
		return nil
	}
	order_ := new(domain.Order)
	order_.ID = o.ID
	if o.X != nil {
		order_.X = o.X.ToDomain()
	}
	if o.Xs != nil {
		order_.Xs = make([]domain.OrderAddress, len(o.Xs))
		for _i, _x := range o.Xs {
			order_.Xs[_i] = *_x.ToDomain()
		}
	}
	o.writeDomain(order_)
	return order_
}

// FromDomain reads from type domain.Order, then writes back to receiver and returns it
func (o *Order) FromDomain(order_ *domain.Order) *Order {
	if order_ == nil {
		return o
	}
	if o == nil {
		o = new(Order)
	}
	o.ID = order_.ID
	o.readDomain(order_)
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o Order) ShootMap() { /*noop*/ }
