// Code generated by "shoot map -path=../../domain/model -alias=domain -type=Order,OrderAddress"; DO NOT EDIT.

package dto

import domain "mappersample/domain/model"

// ToDomain converts receiver to type domain.OrderAddress
func (o *OrderAddress) ToDomain() *domain.OrderAddress {
	if o == nil {
		return nil
	}
	orderAddress_ := new(domain.OrderAddress)
	orderAddress_.City = o.City
	orderAddress_.Street = o.Street
	orderAddress_.Room = o.RoomNum
	return orderAddress_
}

// FromDomain reads from type domain.OrderAddress, then writes back to receiver and returns it
func (o *OrderAddress) FromDomain(orderAddress_ *domain.OrderAddress) *OrderAddress {
	if orderAddress_ == nil {
		return o
	}
	if o == nil {
		o = new(OrderAddress)
	}
	o.City = orderAddress_.City
	o.Street = orderAddress_.Street
	o.RoomNum = orderAddress_.Room
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o OrderAddress) ShootMap() { /*noop*/ }
