// Code generated by "shoot map -path=../../domain/model -type=Order"; DO NOT EDIT.

package dto

import (
	"mappersample/domain/model"

	"github.com/shopspring/decimal"
)

// ToModel converts receiver to type model.Order
func (o *Order) ToModel() *model.Order {
	order_ := new(model.Order)
	order_.ID = o.ID
	order_.Amount = o.StringToDecimal(o.Amount)
	order_.Status = o.Status
	order_.OrderTime = o.StringToTime(o.OrderingTime)
	order_.Price = model.Price(o.Price)
	order_.Price2 = o.Price2
	order_.Value = int32(o.Value)
	o.writeModel(order_)
	return order_
}

// FromModel read from type model.Order, then write back to receiver
func (o *Order) FromModel(order_ *model.Order) *Order {
	o.ID = order_.ID
	o.Amount = o.DecimalToString(order_.Amount)
	o.Status = order_.Status
	o.OrderingTime = o.TimeToString(order_.OrderTime)
	o.Price = decimal.Decimal(o.Price)
	o.Price2 = order_.Price2
	o.Value = int(o.Value)
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o Order) ShootMap() { /*noop*/ }
