// Code generated by "shoot map -path=../../domain/model -type=Order"; DO NOT EDIT.

package dto

import "mappersample/domain/model"

// ToModel converts receiver to type model.Order
func (o *Order) ToModel() *model.Order {
	order_ := new(model.Order)
	order_.Status = o.Status
	order_.Int = int32(o.Int)
	order_.Price = model.Price(o.Price)
	order_.Amount = o.StringToDecimal(o.Amount)
	order_.OrderTime = o.StringToTime(o.OrderingTime)
	o.writeModel(order_)
	return order_
}

// FromModel read from type model.Order, then write back to receiver
func (o *Order) FromModel(order_ *model.Order) *Order {
	o.Status = order_.Status
	o.Amount = o.DecimalToString(order_.Amount)
	o.OrderingTime = o.TimeToString(order_.OrderTime)
	o.readModel(*order_)
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o Order) ShootMap() { /*noop*/ }
