// Code generated by "shoot map -path=../../domain/model -type=User"; DO NOT EDIT.

package dto

import "mappersample/domain/model"

// ToModel converts receiver to type model.User
func (u *User) ToModel() *model.User {
	user_ := new(model.User)
	user_.Email = u.Email
	user_.ID = u.ID
	u.toModel(user_)
	return user_
}

// FromModel read from type model.User, then write back to receiver
func (u *User) FromModel(user_ *model.User) *User {
	u.Email = user_.Email
	u.ID = user_.ID
	u.fromModel(*user_)
	return u
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (u User) ShootMap() { /*noop*/ }
