// Code generated by "shoot new -getset -json -type=Order"; DO NOT EDIT. (v0.5.0-beta.1)

package embed

import "encoding/json"

// NewOrder constructs a new instance of type Order
func NewOrder(id uint, status string) *Order {
	return &Order{
		Base: &Base{
			id: id,
		},
		status: status,
	}
}

// Status gets the value of field status
func (o *Order) Status() string {
	return o.status
}

// SetStatus sets the value of field status
func (o *Order) SetStatus(status_ string) {
	o.status = status_
}

type _json_Order struct {
	Id     uint   `json:"id"`
	Status string `json:"status"`
}

// MarshalJSON serializes type Order to json bytes
func (o Order) MarshalJSON() ([]byte, error) {
	data := _json_Order{
		Id:     o.Id(),
		Status: o.Status(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Order
func (o *Order) UnmarshalJSON(data []byte) error {
	var order_ _json_Order
	if err := json.Unmarshal(data, &order_); err != nil {
		return err
	}
	o.SetId(order_.Id)
	o.SetStatus(order_.Status)
	return nil
}

// OrderGetter is read-only interface for Order type
type OrderGetter interface {
	BaseGetter
	Status() string
}

// OrderSetter is write-only interface for Order type
type OrderSetter interface {
	BaseSetter
	SetStatus(string)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Order) ShootNew() { /*noop*/ }
