// Code generated by "shoot new -getset -json -type=Order"; DO NOT EDIT. (v0.4.2-beta.2)

package embed

import "encoding/json"

// NewOrder constructs a new instance of type Order
func NewOrder(id uint, status string) *Order {
	return &Order{
		Base: &Base{
			id: id,
		},
		status: status,
	}
}

// Status gets the value of field status
func (o *Order) Status() string {
	return o.status
}

// SetStatus sets the value of field status
func (o *Order) SetStatus(status_ string) {
	o.status = status_
}

type _marshal_Order struct {
	Status string `json:"status"`
}

type _unmarshal_Order struct {
	Status string `json:"status"`
}

// MarshalJSON serializes type Order to json bytes
func (o Order) MarshalJSON() ([]byte, error) {
	data := _marshal_Order{
		Status: o.Status(),
	}
	values := make(map[string]interface{})
	j0, err := json.Marshal(o.Base)
	if err != nil {
		return nil, err
	}
	err = json.Unmarshal(j0, &values)
	if err != nil {
		return nil, err
	}
	j, err := json.Marshal(data)
	if err != nil {
		return nil, err
	}
	err = json.Unmarshal(j, &values)
	if err != nil {
		return nil, err
	}
	return json.Marshal(values)
}

// UnmarshalJSON deserializes json bytes to type Order
func (o *Order) UnmarshalJSON(data []byte) error {
	var order_ _unmarshal_Order
	if err := json.Unmarshal(data, &order_); err != nil {
		return err
	}
	o.SetStatus(order_.Status)
	all := make(map[string]interface{})
	err := json.Unmarshal(data, &all)
	if err != nil {
		return err
	}
	j, err := json.Marshal(order_)
	if err != nil {
		return err
	}
	some := make(map[string]interface{})
	err = json.Unmarshal(j, &some)
	if err != nil {
		return err
	}
	for key := range some {
		delete(all, key)
	}
	jrest, err := json.Marshal(all)
	if err != nil {
		return err
	}
	err = json.Unmarshal(jrest, &o.Base)
	if err != nil {
		return err
	}
	return nil
}

// OrderGetter is read-only interface for Order type
type OrderGetter interface {
	BaseGetter
	Status() string
}

// OrderSetter is write-only interface for Order type
type OrderSetter interface {
	BaseSetter
	SetStatus(string)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Order) ShootNew() { /*noop*/ }
