// Code generated by "shoot map -path=../../domain/model -alias=domain -type=*"; DO NOT EDIT. (v0.7.0-beta.2)

package dto

import domain "mapperexample2/domain/model"

// ToDomain converts receiver to type domain.Order
func (o *Order) ToDomain() *domain.Order {
	if o == nil {
		return nil
	}
	order_ := domain.NewOrder(
		o.Id(),                           //id
		o.StringToDecimal(o.Amount()),    //amount
		o.StringToTime(o.OrderingTime()), //orderTime
		domain.OrderAddress{},            //address
		o.X(),                            //x
		"",                               //y
	)
	oAddress := o.Address()
	if oAddress != nil {
		order_.SetAddress(*oAddress.ToDomain())
	}
	o.writeDomain(order_)
	return order_
}

// FromDomain reads from type domain.Order, then writes back to receiver and returns it
func (o *Order) FromDomain(order_ *domain.Order) *Order {
	if order_ == nil {
		return nil
	}
	_o_ := NewOrder(
		order_.Id(),                        //id
		o.DecimalToString(order_.Amount()), //amount
		"",                                 //orderingTime
		nil,                                //address
		order_.X(),                         //x
		order_.Y(),                         //y
	)
	if o == nil {
		o = _o_
	} else {
		*o = *_o_
	}
	order_Address := order_.Address()
	o.SetAddress(new(OrderAddress).FromDomain(&order_Address))
	o.SetOrderingTime(o.TimeToString(order_.OrderTime()))
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o Order) ShootMap() { /*noop*/ }

// ToDomain converts receiver to type domain.OrderAddress
func (o *OrderAddress) ToDomain() *domain.OrderAddress {
	if o == nil {
		return nil
	}
	orderAddress_ := domain.NewOrderAddress(
		o.City(),    //city
		o.Street(),  //street
		o.RoomNum(), //room
	)
	o.writeDomain(orderAddress_)
	return orderAddress_
}

// FromDomain reads from type domain.OrderAddress, then writes back to receiver and returns it
func (o *OrderAddress) FromDomain(orderAddress_ *domain.OrderAddress) *OrderAddress {
	if orderAddress_ == nil {
		return nil
	}
	_o_ := NewOrderAddress(
		orderAddress_.City(),   //city
		orderAddress_.Street(), //street
		"",                     //roomNum
	)
	if o == nil {
		o = _o_
	} else {
		*o = *_o_
	}
	o.SetRoomNum(orderAddress_.Room())
	o.readDomain(orderAddress_)
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o OrderAddress) ShootMap() { /*noop*/ }
