// Code generated by "shoot new -getset -type=Order2 -ver=test"; DO NOT EDIT. (test)

package dest

import (
	"time"
)

// NewOrder2 constructs a new instance of type Order2
func NewOrder2(id string, amount Decimal, orderTime time.Time, addr0 OrderAddress, addr1 OrderAddress, addr2 *OrderAddress, addr3 *OrderAddress) *Order2 {
	return &Order2{
		id:        id,
		amount:    amount,
		orderTime: orderTime,
		addr0:     addr0,
		addr1:     addr1,
		addr2:     addr2,
		addr3:     addr3,
	}
}

// Id gets the value of field id
func (o *Order2) Id() string {
	return o.id
}

// Amount gets the value of field amount
func (o *Order2) Amount() Decimal {
	return o.amount
}

// OrderTime gets the value of field orderTime
func (o *Order2) OrderTime() time.Time {
	return o.orderTime
}

// Addr0 gets the value of field addr0
func (o *Order2) Addr0() OrderAddress {
	return o.addr0
}

// Addr1 gets the value of field addr1
func (o *Order2) Addr1() OrderAddress {
	return o.addr1
}

// Addr2 gets the value of field addr2
func (o *Order2) Addr2() *OrderAddress {
	return o.addr2
}

// Addr3 gets the value of field addr3
func (o *Order2) Addr3() *OrderAddress {
	return o.addr3
}

// SetId sets the value of field id
func (o *Order2) SetId(id_ string) {
	o.id = id_
}

// SetAmount sets the value of field amount
func (o *Order2) SetAmount(amount_ Decimal) {
	o.amount = amount_
}

// SetOrderTime sets the value of field orderTime
func (o *Order2) SetOrderTime(orderTime_ time.Time) {
	o.orderTime = orderTime_
}

// SetAddr0 sets the value of field addr0
func (o *Order2) SetAddr0(addr0_ OrderAddress) {
	o.addr0 = addr0_
}

// SetAddr1 sets the value of field addr1
func (o *Order2) SetAddr1(addr1_ OrderAddress) {
	o.addr1 = addr1_
}

// SetAddr2 sets the value of field addr2
func (o *Order2) SetAddr2(addr2_ *OrderAddress) {
	o.addr2 = addr2_
}

// SetAddr3 sets the value of field addr3
func (o *Order2) SetAddr3(addr3_ *OrderAddress) {
	o.addr3 = addr3_
}

// Order2Getter is read-only interface for Order2 type
type Order2Getter interface {
	Id() string
	Amount() Decimal
	OrderTime() time.Time
	Addr0() OrderAddress
	Addr1() OrderAddress
	Addr2() *OrderAddress
	Addr3() *OrderAddress
}

// Order2Setter is write-only interface for Order2 type
type Order2Setter interface {
	SetId(string)
	SetAmount(Decimal)
	SetOrderTime(time.Time)
	SetAddr0(OrderAddress)
	SetAddr1(OrderAddress)
	SetAddr2(*OrderAddress)
	SetAddr3(*OrderAddress)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Order2) ShootNew() { /*noop*/ }
