// Code generated by "shoot new -json -type=*"; DO NOT EDIT. (v0.6.1-beta.4)

package dto

import (
	"mappersample/domain/enums"
	"mappersample/infra/mapper"
)

// NewOrder constructs a new instance of type Order
func NewOrder(id string, amount string, status enums.OrderStatus, orderingTime string, address *OrderAddress, x string, y string) *Order {
	return &Order{
		Mapper:       &mapper.Mapper{},
		id:           id,
		amount:       amount,
		status:       status,
		orderingTime: orderingTime,
		address:      address,
		x:            x,
		y:            y,
	}
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Order) ShootNew() { /*noop*/ }

// NewOrderAddress constructs a new instance of type OrderAddress
func NewOrderAddress(city string, street string, roomNum string) *OrderAddress {
	return &OrderAddress{
		city:    city,
		street:  street,
		roomNum: roomNum,
	}
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o OrderAddress) ShootNew() { /*noop*/ }
