// Code generated by "shoot new -getset -json -type=*"; DO NOT EDIT. (v0.6.1-beta.3)

package dto

import (
	"encoding/json"
	"mappersample/domain/enums"
	"mappersample/infra/mapper"
)

// NewOrder constructs a new instance of type Order
func NewOrder(id string, amount string, status enums.OrderStatus, orderingTime string, address *OrderAddress, x string, y string) *Order {
	return &Order{
		Mapper:       &mapper.Mapper{},
		id:           id,
		amount:       amount,
		status:       status,
		orderingTime: orderingTime,
		address:      address,
		x:            x,
		y:            y,
	}
}

// Id gets the value of field id
func (o *Order) Id() string {
	return o.id
}

// Amount gets the value of field amount
func (o *Order) Amount() string {
	return o.amount
}

// Status gets the value of field status
func (o *Order) Status() enums.OrderStatus {
	return o.status
}

// OrderingTime gets the value of field orderingTime
func (o *Order) OrderingTime() string {
	return o.orderingTime
}

// Address gets the value of field address
func (o *Order) Address() *OrderAddress {
	return o.address
}

// X gets the value of field x
func (o *Order) X() string {
	return o.x
}

// SetId sets the value of field id
func (o *Order) SetId(id_ string) {
	o.id = id_
}

// SetAmount sets the value of field amount
func (o *Order) SetAmount(amount_ string) {
	o.amount = amount_
}

// SetStatus sets the value of field status
func (o *Order) SetStatus(status_ enums.OrderStatus) {
	o.status = status_
}

// SetOrderingTime sets the value of field orderingTime
func (o *Order) SetOrderingTime(orderingTime_ string) {
	o.orderingTime = orderingTime_
}

// SetAddress sets the value of field address
func (o *Order) SetAddress(address_ *OrderAddress) {
	o.address = address_
}

// SetY sets the value of field y
func (o *Order) SetY(y_ string) {
	o.y = y_
}

type _json_Order struct {
	Id           string            `json:"id"`
	Amount       string            `json:"amount"`
	Status       enums.OrderStatus `json:"status"`
	OrderingTime string            `json:"orderingTime"`
	Address      *OrderAddress     `json:"address"`
	X            string            `json:"x"`
	Y            string            `json:"y"`
}

// MarshalJSON serializes type Order to json bytes
func (o Order) MarshalJSON() ([]byte, error) {
	data := _json_Order{
		Id:           o.Id(),
		Amount:       o.Amount(),
		Status:       o.Status(),
		OrderingTime: o.OrderingTime(),
		Address:      o.Address(),
		X:            o.X(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Order
func (o *Order) UnmarshalJSON(data []byte) error {
	var order_ _json_Order
	if err := json.Unmarshal(data, &order_); err != nil {
		return err
	}
	o.SetId(order_.Id)
	o.SetAmount(order_.Amount)
	o.SetStatus(order_.Status)
	o.SetOrderingTime(order_.OrderingTime)
	o.SetAddress(order_.Address)
	o.SetY(order_.Y)
	return nil
}

// OrderGetter is read-only interface for Order type
type OrderGetter interface {
	Id() string
	Amount() string
	Status() enums.OrderStatus
	OrderingTime() string
	Address() *OrderAddress
	X() string
}

// OrderSetter is write-only interface for Order type
type OrderSetter interface {
	SetId(string)
	SetAmount(string)
	SetStatus(enums.OrderStatus)
	SetOrderingTime(string)
	SetAddress(*OrderAddress)
	SetY(string)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Order) ShootNew() { /*noop*/ }

// NewOrderAddress constructs a new instance of type OrderAddress
func NewOrderAddress(city string, street string, roomNum string) *OrderAddress {
	return &OrderAddress{
		city:    city,
		street:  street,
		roomNum: roomNum,
	}
}

// City gets the value of field city
func (o *OrderAddress) City() string {
	return o.city
}

// Street gets the value of field street
func (o *OrderAddress) Street() string {
	return o.street
}

// RoomNum gets the value of field roomNum
func (o *OrderAddress) RoomNum() string {
	return o.roomNum
}

// SetCity sets the value of field city
func (o *OrderAddress) SetCity(city_ string) {
	o.city = city_
}

// SetStreet sets the value of field street
func (o *OrderAddress) SetStreet(street_ string) {
	o.street = street_
}

// SetRoomNum sets the value of field roomNum
func (o *OrderAddress) SetRoomNum(roomNum_ string) {
	o.roomNum = roomNum_
}

type _json_OrderAddress struct {
	City    string `json:"city"`
	Street  string `json:"street"`
	RoomNum string `json:"roomNum"`
}

// MarshalJSON serializes type OrderAddress to json bytes
func (o OrderAddress) MarshalJSON() ([]byte, error) {
	data := _json_OrderAddress{
		City:    o.City(),
		Street:  o.Street(),
		RoomNum: o.RoomNum(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type OrderAddress
func (o *OrderAddress) UnmarshalJSON(data []byte) error {
	var orderAddress_ _json_OrderAddress
	if err := json.Unmarshal(data, &orderAddress_); err != nil {
		return err
	}
	o.SetCity(orderAddress_.City)
	o.SetStreet(orderAddress_.Street)
	o.SetRoomNum(orderAddress_.RoomNum)
	return nil
}

// OrderAddressGetter is read-only interface for OrderAddress type
type OrderAddressGetter interface {
	City() string
	Street() string
	RoomNum() string
}

// OrderAddressSetter is write-only interface for OrderAddress type
type OrderAddressSetter interface {
	SetCity(string)
	SetStreet(string)
	SetRoomNum(string)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o OrderAddress) ShootNew() { /*noop*/ }
