// Code generated by "shoot map -path=../../domain/model -alias=domain -type=*"; DO NOT EDIT. (v0.3.3-beta.1)

package dto

import domain "github.com/lopolopen/shoot/samples/mapper-sample2/domain/model"

// ToDomain converts receiver to type domain.Order
func (o *Order) ToDomain() *domain.Order {
	if o == nil {
		return nil
	}
	order_ := new(domain.Order)
	order_.SetId(o.Id())
	order_.SetAmount(o.StringToDecimal(o.Amount()))
	order_.SetStatus(o.Status())
	order_.SetOrderTime(o.StringToTime(o.OrderingTime()))
	oAddress := o.Address()
	order_.SetAddress(*oAddress.ToDomain())
	o.writeDomain(order_)
	return order_
}

// FromDomain reads from type domain.Order, then writes back to receiver and returns it
func (o *Order) FromDomain(order_ *domain.Order) *Order {
	if order_ == nil {
		return o
	}
	if o == nil {
		o = new(Order)
	}
	o.SetId(order_.Id())
	o.SetAmount(o.DecimalToString(order_.Amount()))
	o.SetStatus(order_.Status())
	o.SetOrderingTime(o.TimeToString(order_.OrderTime()))
	order_Address := order_.Address()
	o.SetAddress(new(OrderAddress).FromDomain(&order_Address))
	o.readDomain(order_)
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o Order) ShootMap() { /*noop*/ }

// ToDomain converts receiver to type domain.OrderAddress
func (o *OrderAddress) ToDomain() *domain.OrderAddress {
	if o == nil {
		return nil
	}
	orderAddress_ := new(domain.OrderAddress)
	orderAddress_.SetCity(o.City())
	orderAddress_.SetStreet(o.Street())
	orderAddress_.SetRoom(o.RoomNum())
	o.writeDomain(orderAddress_)
	return orderAddress_
}

// FromDomain reads from type domain.OrderAddress, then writes back to receiver and returns it
func (o *OrderAddress) FromDomain(orderAddress_ *domain.OrderAddress) *OrderAddress {
	if orderAddress_ == nil {
		return o
	}
	if o == nil {
		o = new(OrderAddress)
	}
	o.SetCity(orderAddress_.City())
	o.SetStreet(orderAddress_.Street())
	o.SetRoomNum(orderAddress_.Room())
	o.readDomain(orderAddress_)
	return o
}

// ShootMap exists solely to fulfill the MapShooter interface contract
func (o OrderAddress) ShootMap() { /*noop*/ }
