// Code generated by "shoot new -getset -type=*"; DO NOT EDIT. (v0.3.3-beta.1)

package model

import (
	"mappersample/domain/enums"
	"time"

	"github.com/shopspring/decimal"
)

// NewOrder constructs a new instance of type Order
func NewOrder(id string, amount decimal.Decimal, status enums.OrderStatus, orderTime time.Time, address OrderAddress) *Order {
	return &Order{
		id:        id,
		amount:    amount,
		status:    status,
		orderTime: orderTime,
		address:   address,
	}
}

// Id gets the value of field id
func (o *Order) Id() string {
	return o.id
}

// Amount gets the value of field amount
func (o *Order) Amount() decimal.Decimal {
	return o.amount
}

// Status gets the value of field status
func (o *Order) Status() enums.OrderStatus {
	return o.status
}

// OrderTime gets the value of field orderTime
func (o *Order) OrderTime() time.Time {
	return o.orderTime
}

// Address gets the value of field address
func (o *Order) Address() OrderAddress {
	return o.address
}

// SetId sets the value of field id
func (o *Order) SetId(id_ string) {
	o.id = id_
}

// SetAmount sets the value of field amount
func (o *Order) SetAmount(amount_ decimal.Decimal) {
	o.amount = amount_
}

// SetStatus sets the value of field status
func (o *Order) SetStatus(status_ enums.OrderStatus) {
	o.status = status_
}

// SetOrderTime sets the value of field orderTime
func (o *Order) SetOrderTime(orderTime_ time.Time) {
	o.orderTime = orderTime_
}

// SetAddress sets the value of field address
func (o *Order) SetAddress(address_ OrderAddress) {
	o.address = address_
}

// OrderGetter is read-only interface for Order type
type OrderGetter interface {
	Id() string
	Amount() decimal.Decimal
	Status() enums.OrderStatus
	OrderTime() time.Time
	Address() OrderAddress
}

// OrderSetter is write-only interface for Order type
type OrderSetter interface {
	SetId(string)
	SetAmount(decimal.Decimal)
	SetStatus(enums.OrderStatus)
	SetOrderTime(time.Time)
	SetAddress(OrderAddress)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Order) ShootNew() { /*noop*/ }

// NewOrderAddress constructs a new instance of type OrderAddress
func NewOrderAddress(city string, street string, room string) *OrderAddress {
	return &OrderAddress{
		city:   city,
		street: street,
		room:   room,
	}
}

// City gets the value of field city
func (o *OrderAddress) City() string {
	return o.city
}

// Street gets the value of field street
func (o *OrderAddress) Street() string {
	return o.street
}

// Room gets the value of field room
func (o *OrderAddress) Room() string {
	return o.room
}

// SetCity sets the value of field city
func (o *OrderAddress) SetCity(city_ string) {
	o.city = city_
}

// SetStreet sets the value of field street
func (o *OrderAddress) SetStreet(street_ string) {
	o.street = street_
}

// SetRoom sets the value of field room
func (o *OrderAddress) SetRoom(room_ string) {
	o.room = room_
}

// OrderAddressGetter is read-only interface for OrderAddress type
type OrderAddressGetter interface {
	City() string
	Street() string
	Room() string
}

// OrderAddressSetter is write-only interface for OrderAddress type
type OrderAddressSetter interface {
	SetCity(string)
	SetStreet(string)
	SetRoom(string)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o OrderAddress) ShootNew() { /*noop*/ }
