// Code generated by "shoot new -getset -json -file=new_json.go -ver=test"; DO NOT EDIT. (test)

package ctor

import "encoding/json"

// NewBaseJSON constructs a new instance of type BaseJSON
func NewBaseJSON(z string, b int, a string) *BaseJSON {
	return &BaseJSON{
		z: z,
		b: b,
		a: a,
	}
}

// Z gets the value of field z
func (b *BaseJSON) Z() string {
	return b.z
}

// B gets the value of field b
func (b *BaseJSON) B() int {
	return b.b
}

// A gets the value of field a
func (b *BaseJSON) A() string {
	return b.a
}

// SetZ sets the value of field z
func (b *BaseJSON) SetZ(z_ string) {
	b.z = z_
}

// SetB sets the value of field b
func (b *BaseJSON) SetB(b_ int) {
	b.b = b_
}

// SetA sets the value of field a
func (b *BaseJSON) SetA(a_ string) {
	b.a = a_
}

type _json_BaseJSON struct {
	Z string `json:"z"`
	B int    `json:"b"`
	A string `json:"a"`
}

// MarshalJSON serializes type BaseJSON to json bytes
func (b BaseJSON) MarshalJSON() ([]byte, error) {
	data := _json_BaseJSON{
		Z: b.Z(),
		B: b.B(),
		A: b.A(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type BaseJSON
func (b *BaseJSON) UnmarshalJSON(data []byte) error {
	var baseJSON_ _json_BaseJSON
	if err := json.Unmarshal(data, &baseJSON_); err != nil {
		return err
	}
	b.SetZ(baseJSON_.Z)
	b.SetB(baseJSON_.B)
	b.SetA(baseJSON_.A)
	return nil
}

// BaseJSONGetter is read-only interface for BaseJSON type
type BaseJSONGetter interface {
	Z() string
	B() int
	A() string
}

// BaseJSONSetter is write-only interface for BaseJSON type
type BaseJSONSetter interface {
	SetZ(string)
	SetB(int)
	SetA(string)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (b BaseJSON) ShootNew() { /*noop*/ }

// NewOther constructs a new instance of type Other
func NewOther(name string, age int) *Other {
	return &Other{
		Name: name,
		Age:  age,
	}
}

type _json_Other struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

// MarshalJSON serializes type Other to json bytes
func (o Other) MarshalJSON() ([]byte, error) {
	data := _json_Other{
		Name: o.Name,
		Age:  o.Age,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Other
func (o *Other) UnmarshalJSON(data []byte) error {
	var other_ _json_Other
	if err := json.Unmarshal(data, &other_); err != nil {
		return err
	}
	o.Name = other_.Name
	o.Age = other_.Age
	return nil
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (o Other) ShootNew() { /*noop*/ }

// NewSonJSON constructs a new instance of type SonJSON
func NewSonJSON(z string, b int, a string, y int, x int, other Other) *SonJSON {
	return &SonJSON{
		BaseJSON: BaseJSON{
			z: z,
			b: b,
			a: a,
		},
		y:     y,
		x:     x,
		Other: other,
	}
}

// Y gets the value of field y
func (s *SonJSON) Y() int {
	return s.y
}

// X gets the value of field x
func (s *SonJSON) X() int {
	return s.x
}

// SetY sets the value of field y
func (s *SonJSON) SetY(y_ int) {
	s.y = y_
}

// SetX sets the value of field x
func (s *SonJSON) SetX(x_ int) {
	s.x = x_
}

type _json_SonJSON struct {
	Z     string `json:"z"`
	B     int    `json:"b"`
	A     string `json:"a"`
	Y     int    `json:"y"`
	X     int    `json:"x"`
	Other Other  `json:"other"`
}

// MarshalJSON serializes type SonJSON to json bytes
func (s SonJSON) MarshalJSON() ([]byte, error) {
	data := _json_SonJSON{
		Z:     s.Z(),
		B:     s.B(),
		A:     s.A(),
		Y:     s.Y(),
		X:     s.X(),
		Other: s.Other,
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type SonJSON
func (s *SonJSON) UnmarshalJSON(data []byte) error {
	var sonJSON_ _json_SonJSON
	if err := json.Unmarshal(data, &sonJSON_); err != nil {
		return err
	}
	s.SetZ(sonJSON_.Z)
	s.SetB(sonJSON_.B)
	s.SetA(sonJSON_.A)
	s.SetY(sonJSON_.Y)
	s.SetX(sonJSON_.X)
	s.Other = sonJSON_.Other
	return nil
}

// SonJSONGetter is read-only interface for SonJSON type
type SonJSONGetter interface {
	BaseJSONGetter
	Y() int
	X() int
}

// SonJSONSetter is write-only interface for SonJSON type
type SonJSONSetter interface {
	BaseJSONSetter
	SetY(int)
	SetX(int)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (s SonJSON) ShootNew() { /*noop*/ }
