// Code generated by "shoot new -getset -json -type=Base"; DO NOT EDIT. (v0.7.0-beta.2)

package embed

import "encoding/json"

// NewBase constructs a new instance of type Base
func NewBase(id uint) *Base {
	return &Base{
		id: id,
	}
}

// Id gets the value of field id
func (b *Base) Id() uint {
	return b.id
}

// SetId sets the value of field id
func (b *Base) SetId(id_ uint) {
	b.id = id_
}

type _json_Base struct {
	Id uint `json:"id"`
}

// MarshalJSON serializes type Base to json bytes
func (b Base) MarshalJSON() ([]byte, error) {
	data := _json_Base{
		Id: b.Id(),
	}
	return json.Marshal(data)
}

// UnmarshalJSON deserializes json bytes to type Base
func (b *Base) UnmarshalJSON(data []byte) error {
	var base_ _json_Base
	if err := json.Unmarshal(data, &base_); err != nil {
		return err
	}
	b.SetId(base_.Id)
	return nil
}

// BaseGetter is read-only interface for Base type
type BaseGetter interface {
	Id() uint
}

// BaseSetter is write-only interface for Base type
type BaseSetter interface {
	SetId(uint)
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (b Base) ShootNew() { /*noop*/ }
